### ISSUE TITLE
May we inquire when the source code will be made available(for those that can't take a joke)

### ISSUE THREAD

**Issue by shanedickson** [ProjectDent/ARKit-CoreLocation#1]
As some obviously have no sense of humor, let me clarify:  I'm NOT actually demanding to have the code right now, or I'll go home screaming.  It was a joke.  I wasn't being rude, or disrespectful.  It was a JOKE.

**Comment by UnityEQ** [comment]
agreed

**Comment by jackfreed** [comment]
yup

**Comment by fit4web** [comment]
how about asking it nice and friendly? Or did u pay for anything that u use 4x ! and 4x?

that is disrespectful and RUDE.

Be happy that the owner of the code thinks about sharing this amazing feature! 

shame on you

**Comment by rom4in** [comment]
well said @fit4web  Can't believe some people.......😲

**Comment by gdelafosse** [comment]
I hope Andrew is still motivated to share his job now...

**Comment by shanedickson** [comment]
I'm pretty sure, @fit4web, most people know I wasn't really coming down on the guy.  Get a life, and loosen up.

**Comment by shanedickson** [comment]
I think the demo that shared showed a lot of potential.

**Comment by jlubeck** [comment]
@shanedickson you joined GitHub only 3 months ago, and your first contribution is a ticket (on a repo that wasn't even announced anywhere) demanding code that we still don't know if it's going to be open sourced. Maybe you are the one who needs to loosen up and give the developer space to do what he thinks is best for his code.

**Comment by shanedickson** [comment]
@jlubeck Sigh.  Yet another person who can't tell the difference between a joke and a demand.  For the record, I've been on GitHub a lot longer than three months, just not under this profile, but nice try.  Actually, he said last week that he was going to post it, so yes, we DO know it's going to be open sourced. Why do you think I opened this ticket in the first place.  It's actually a way of saying I admired his demo, and was looking forward to seeing his work.  Maybe you should try keeping up on the subject before you post comments.

**Comment by CameronBanga** [comment]
I'm on the "This sounded dick-ish" side of this argument. Joke or no joke, it's @ProjectDent's code. He can upload or not. Obviously, we're all following because we hope he posts. 

It may have been a joke, but didn't come off like a joke I'd see between developers. It came off more like a post I see from tons of people who aren't programmers, expecting the code and instructions on how to set up immediately and for free.

**Comment by shanedickson** [comment]
Spoken like a true non-dev.  I've written ARKit code.  Have you?  I'm just wanting to compare.  Personally, I could care less where you stand on this "argument".  I have apps to ship.

**Comment by shanedickson** [comment]
In the interest of everyone involved, I'm closing this issue.  Too many trolls and dev wannabe's taking things out of context, and taking attention away from an interesting project.

**Comment by CameronBanga** [comment]
Where's Your Code?????? I wanna see your shipping AR CODE too!

**Comment by chriszielinski** [comment]
<p align="center">
<em>Everyone else</em>
<br>
  <img src="https://media.giphy.com/media/bqFU4zCmAnF2o/giphy.gif">
</p>

**Comment by shanedickson** [comment]
I never said AR code was what I shipped.  I’d wager I have more MAU’s using the code I’ve shipped than anything you could bring to the table.

**Comment by manofsteel9740** [comment]
Actually, this repo is dealing with ARKit, of which there is no shipping code yet.  @CameronBanga, you really need to leave this conversation to the adults in the room.
