### ISSUE TITLE
Switch must be exhaustive

### ISSUE THREAD

**Issue by Rjmaurya13** [ProjectDent/ARKit-CoreLocation#101]
ARCL project gives error after installing it.

Switch must be exhaustive
Do you want to add missing cases?

**Comment by glouel** [comment]
See this patch for the fix : https://github.com/ProjectDent/ARKit-CoreLocation/pull/95

The problem is also mentionned on issue #100

**Comment by aaronbrethorst** [comment]
fixed in #95
