### ISSUE TITLE
Tilt issue when using LocationAnnotationNode

### ISSUE THREAD

**Issue by sungjin0213** [ProjectDent/ARKit-CoreLocation#102]
I'm using LocationAnnotationNode, and the image is drawing fine and displaying where it should be, but somehow it's slightly tilted on the top left.

Sometimes it's most noticeable than the other times, but LocationAnnotationNode's image is pretty consistently tilted.

I thought at first it's the angle I look at it, but although I'm looking at it directly, it's slightly tilted. Any solution for this? Anybody else having this issue?

**Comment by AakashSareen** [comment]
Can you attach a screenshot with PII (personally identifiable info) removed? 
I have experienced the same and I believe it happens when you set arbitrary height. Try setting the height  to of _your_ locationNode to be the same as your current altitude. 

if you're in urgent need, you can add empty LocatioNode (to track location, like an anchor), add a child node with image, add constraints to it, such that your child node is always perpendicular to the -Z axis.

**Comment by sungjin0213** [comment]
@AakashSareen Thanks for the response. Here is screenshot that demonstrate the issue. Top left corner is tilted downward:
![img_0316](https://user-images.githubusercontent.com/1302162/40018091-e4879e2e-5780-11e8-95a2-bbea2fd6d117.jpg)

As you said, I started to notice this once I set heights, however, I cannot remove that feature since I want to be able to set this nodes on certain heights based on my current location.

For your second paragraph, are you suggesting adding additional node other than annotation node itself? So it would be location node > [place holder node for location] > annotation node? 

For adding constraint, would you add billboard constraint? If not, what is the other constraint are you talking about? Thanks.

**Comment by AakashSareen** [comment]
Constraints I have used successfully are billboard and SCNLookAtConstraint with gimbal lock enables which makes sure that your object maintains an ortjogu relationship with the AR world y axis   

Share your repo privately and I can add Comments. 

I have experienced the same. My solution would be to wait before adding nodes for a good reading and maybe even a horizontal plane. 

One more thing, this library is better at larger distances as explained by the author in the wiki(I think)

AR world begins with an approximate value which is revised over time, what's the reproducibility of the issue.

**Comment by AakashSareen** [comment]
Also, I never said that you can't modify hieght, is just that when you initialize a node with 0 altitude, and your position is 100 altitude. You are unintentionally setting the object to be lower than your position. I strongly believe you can solve your problem using gimbalLock

**Comment by intere** [comment]
I'm closing this issue because it's so old and stale.
