### ISSUE TITLE
How can I add the navigation Line like your video demo?

### ISSUE THREAD

**Issue by R-U-N** [ProjectDent/ARKit-CoreLocation#106]
Can you put up  your naviagtion demo totlaly to github?I am so interested of AR Navigation.

**Comment by intere** [comment]
I've also been trying to figure this out, however there are some issues associated with achieving this (see the README file for more info about the true north issue).

**Comment by FouadAstitou** [comment]
Did you guys figure out how to do this?

**Comment by intere** [comment]
This has been accomplished (it's not exactly like the demo - no arrows, but it does show the path); see here: https://github.com/ProjectDent/ARKit-CoreLocation/pull/159
