### ISSUE TITLE
Add 3d model .scn or .dae file at some lat-long

### ISSUE THREAD

**Issue by ArbabR** [ProjectDent/ARKit-CoreLocation#111]
Hi 

Anyway I can add a 3d model node to any lat-long as confirmed location node instead of simple view/image?

**Comment by AakashSareen** [comment]
yes. 
LocationNode is an SCNNode, you can add child nodes to it. 

> ///A location node can be added to a scene using a coordinate.
> ///Its scale and position should not be adjusted, as these are used for scene layout purposes
> ///To adjust the scale and position of items within a node, you can add them to a child node and adjust them there
> open class LocationNode: SCNNode {

**Comment by aaronbrethorst** [comment]
Thank you, @AakashSareen! @ArbabR - feel free to reopen if you encounter an issue with ARCL that prevents you from following Aakash's suggestion.

**Comment by ArbabR** [comment]
@aaronbrethorst sure. Thanks, @AakashSareen for the answer. I have added a model node in location node but haven't been able to see in AR

 let locationNode = LocationNode.init(location: pinLocation) // pinLocation : CLLocation
        locationNode.addChildNode(modelNode) //model node 
        sceneLocationView.addLocationNodeWithConfirmedLocation(locationNode: locationNode)

**Comment by AakashSareen** [comment]
i faced a lot of issues with scale and position in the beginning. Remember in AR world 1 unit is 1 meter. I dont know your model properties but to debug it try adding it as a childNode to pointOfView(property on sceneView), you can set its position to (0,0,-1) (-z is away from phone IIRC)

**Comment by AakashSareen** [comment]
you can also add a regular node to your ARView and set its transform to be same as the LocationNode

**Comment by ArbabR** [comment]
I have debugged the model node it's showing perfectly fine. 

I have added the node as a point of view to the sceneView but the 3d node remains fixed to the AR screen's top. I need to place the node at some location according to my understanding this code should work

let locationNode = LocationNode.init(location: pinLocation) // pinLocation : CLLocation
locationNode.addChildNode(modelNode) //model node
sceneLocationView.addLocationNodeWithConfirmedLocation(locationNode: locationNode)

Do you remember the steps how we can add a 3d model node at some lat-long same as we are doing with the UIImage?
