### ISSUE TITLE
Adding a UIView

### ISSUE THREAD

**Issue by jwilson85** [ProjectDent/ARKit-CoreLocation#114]
So I see how you guys added a UIIMage to the Scene. However, I wanted to add a UIView. So using your code I created the code below. Everything work except one thing. I could not get the background to be transparent. I ended up converting my view to a UIIMage and have a current workaround. However, I think it would be nice if your SDK supported adding UIViews. 

One other odd thing I noticed: When I added the views using: 
`self.sceneLocationView.addLocationNodeWithConfirmedLocation(`. 
They were smaller the farther away. However when I add Images using the same method. They stay the same size no matter the distance. How do i controle that feature? 

```
open class LocationViewNode: LocationNode {
    ///An image to use for the annotation
    ///When viewed from a distance, the annotation will be seen at the size provided
    ///e.g. if the size is 100x100px, the annotation will take up approx 100x100 points on screen.
    public let view: UIView
    
    ///Subnodes and adjustments should be applied to this subnode
    ///Required to allow scaling at the same time as having a 2D 'billboard' appearance
    public let annotationNode: SCNNode
    
    ///Whether the node should be scaled relative to its distance from the camera
    ///Default value (false) scales it to visually appear at the same size no matter the distance
    ///Setting to true causes annotation nodes to scale like a regular node
    ///Scaling relative to distance may be useful with local navigation-based uses
    ///For landmarks in the distance, the default is correct
    public var scaleRelativeToDistance = false
    
    public init(location: CLLocation?, view: UIView) {
        self.view = view
        
        let plane = SCNPlane(width: view.bounds.size.width / 100, height: view.bounds.size.height / 100)
        plane.firstMaterial!.diffuse.contents = view
        plane.firstMaterial!.lightingModel = .constant
        
        annotationNode = SCNNode()
        annotationNode.geometry = plane
        
        super.init(location: location)
        
        let billboardConstraint = SCNBillboardConstraint()
        billboardConstraint.freeAxes = SCNBillboardAxis.Y
        constraints = [billboardConstraint]
        
        addChildNode(annotationNode)
    }
    
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

**Comment by adrgrondin** [comment]
I have ended up with the same solution but however I sometimes get white empty SCNNode without my UIView which is loaded from a Nib. It is not all the nodes but only few and it seems to be random. Do you have the same problem @jwilson85 ?

**Comment by adrgrondin** [comment]
@jwilson85 to improve your code you should use:
```swift
plane.firstMaterial!.diffuse.contents = view.layer
```
Because as [Apple documentation](https://developer.apple.com/documentation/scenekit/scnmaterialproperty/1395372-contents) says:

> SceneKit cannot use a layer that is already being displayed elsewhere (for example, the backing layer of a UIView object).

This is why I had the white SCNNode, using a CALayer is more reliable.

**Comment by jwilson85** [comment]
Thanks I’ll try that

**Comment by KaiKruschel** [comment]
I seem to be having the same problem with the missing UIViews. Adding view.layer instead of the view itself seems to have helped a bit, but instead of white empty views I now sometimes get completely invisible views. Did anyone experience this as well?

**Comment by yogendragirase55** [comment]
@adrgrondin 
plane.firstMaterial!.diffuse.contents = view.layer 

I have used the above your code but not getting events for button so my question is how can i get buttons events?
