### ISSUE TITLE
Incompatibility with relocalization API

### ISSUE THREAD

**Issue by futuretap** [ProjectDent/ARKit-CoreLocation#124]
I tried adding

    public func sessionShouldAttemptRelocalization(_ session: ARSession) -> Bool {
        return true
    }

 to `SceneLocationView.swift` in order to support the relocalizing feature introduced in ARKit 1.5 (iOS 11.3). Unfortunately, when putting the app in the background and back into foreground, it deadlocks on the main thread.

**Comment by intere** [comment]
@futuretap - have you dug into this any more and figured out what the issue is?
