### ISSUE TITLE
CPU workload rising while staying in the same position

### ISSUE THREAD

**Issue by KaiKruschel** [ProjectDent/ARKit-CoreLocation#126]
I had a problem where the app would slow down more and more with time while not changing the scene. At first I thought this was a problem with my memory management, but through the help of a colleague we found that in SceneLocationView.swift there is an array SceneLocationEstimates that gets a new value added every second in addSceneLocationEstimate. 

There is functionality that gets called to cull this array again(removeOldLocationEstimates), but it only filters out estimates that are more than a specified radius removed from the current location.

This means, if the user stays in the same place the array keeps growing and eventually slowing down the app through the constant sorting.

Capping the array size and constantly removing old elements fixes this issue for me.

**Comment by intere** [comment]
@KaiKruschel - Would you please submit a PR for this issue?
