### ISSUE TITLE
Tap On Marker Does't Work

### ISSUE THREAD

**Issue by gosaitarun** [ProjectDent/ARKit-CoreLocation#127]
Hello,

I have implemented ARKit-CoreLocation in our application with custom UIView which includes a button, two labels a small image icon. When I click on the button, it does not perform any action on the button. Sometimes it's work and Sometimes not. I'm just navigating from one view controller to another controller on button action.

Thank!

**Comment by intere** [comment]
@gosaitarun - this doesn't sound like an issue with the library, this sounds like an issue with the UI you're building.  Have you use the UI Debugger to see if you've got a view sitting on top of another?

**Comment by prabasdm** [comment]
@intere, I have added multiple pin images on AR mode with different details. Now I have to show the details of the pin when it gets click/tap in AR mode. How to find the particular pin got click action?

**Comment by orest22** [comment]
Register gesture recognizer
`let tapRecognizer = UITapGestureRecognizer(target: self, action: #selector(self.locationTapped(tapRecognizer:)))
            sceneLocationView.addGestureRecognizer(tapRecognizer)
            sceneLocationView.isUserInteractionEnabled = true`

Then implement your handler
`@objc func locationTapped(tapRecognizer: UITapGestureRecognizer) {
        if tapRecognizer.state == UIGestureRecognizerState.ended {
            let sceneView = sceneLocationView as SCNView
            let hits = sceneView.hitTest(tapRecognizer.location(in: tapRecognizer.view), options: nil) as [SCNHitTestResult]
            let hit = hits.first?.node.parent
           // debug your hit it should have the tag you can use
        }
    }`

Something like that.

**Comment by gosaitarun** [comment]
It's working....!!! 
Thanks! @orest22
