### ISSUE TITLE
Looking for a bit of distance assistance. 

### ISSUE THREAD

**Issue by Buckley-James** [ProjectDent/ARKit-CoreLocation#128]
I have added a uiview instead of the image and was looking to have a distance label which updates as the user gets closer to the location.  Has anybody else tried this using Andrews framework?

Thanks

james

**Comment by intere** [comment]
@Jamarsoft - this is trivial to do.  Essentially it would be to do the following:
1.  Add a label to the UI
2. Inside the `updateUserLocation`, if we have a user location then:
3. Compute the distance using [CLLocation.distance(from: CLLocation](https://developer.apple.com/documentation/corelocation/cllocation/1423689-distance)
4. Update the label with that distance

**Comment by elga2** [comment]
@intere @Buckley-James Hi. Would either of you have example code for how this could work please?
