### ISSUE TITLE
App freeze 2-3 seconds after launch

### ISSUE THREAD

**Issue by Darcelsan** [ProjectDent/ARKit-CoreLocation#131]
Hello, 
I'm trying to use the Xcode demo project of ARKit + CoreLocation but the application always freeze 2-3 seconds after launch. Only the time displayed in the left bottom still works. Is this a known issue ? It appears on every branch of this git :/

**Comment by almaleh** [comment]
Hi, this issue happens when you try to get True North data while your compass calibration is disabled.

You can either: 
1- use magnetic north instead of true north
2- enable compass calibration in your device Settings > Privacy > Location Services > System Services

**Comment by Darcelsan** [comment]
> Hi, this issue happens when you try to get True North data while your compass calibration is disabled.
> 
> You can either:
> 1- use magnetic north instead of true north
> 2- enable compass calibration in your device Settings > Privacy > Location Services > System Services

Thank you ! I enabled compass calibration and it works ! :)

**Comment by aaronbrethorst** [comment]
Thanks @almaleh!

**Comment by JacoGasp** [comment]
In my case I'm not able to get the True North working. I have Compass Calibration activated, tried to reset Location Settings but I always receive **CMErrorTrueNorthNotAvailable**.

The only way for me is to set `sceneLocationView.orientToTrueNorth = false`
