### ISSUE TITLE
In case of background to foreground.

### ISSUE THREAD

**Issue by anshulkumar189** [ProjectDent/ARKit-CoreLocation#132]
When application set on background and come back active the markers change the position. Issue attached show in attachment.
![fullsizeoutput_4](https://user-images.githubusercontent.com/33979752/46273709-4e93fe00-c574-11e8-8026-f6909693ae94.jpeg)
![fullsizeoutput_7](https://user-images.githubusercontent.com/33979752/46273710-4f2c9480-c574-11e8-98cf-44e7e1176a87.jpeg)

**Comment by arjohnston** [comment]
I'm running into this same issue when there is any type of reloading the scene and the currentLocation (most notably the heading) has changed. I can be moving from background -> foreground or recovering nodes from the devices memory on entry

I've had success from utilizing removeAllNodes() and then re-initializing in the appdelegate's applicationWillEnterForeground. I do this by saving all nodes into UserDefaults when a a node is created (saving lat, long & alt), and then initializing a function that's similar to the demo's buildNodes function

With that said, I'm in a location where there is limited-to-no-cellular, so the locations are wonky in any case. The largest issue I'm running into at this point is pinning a node at a given location and not having it move on it's own when the heading is changing slightly (movements of 10m+ at a time when within 100m of the node)

**Comment by anshulkumar189** [comment]
thanks Andrew

**Comment by anshulkumar189** [comment]
I have also same problem the nodes are moving one location to another when device is shaking.

**Comment by rofsky** [comment]
Hello @arjohnston and @anshulkumar189 
I am also facing same issue. Have you got solution to this problem ?
Thank you :)

**Comment by Nilesh04** [comment]
Hello @arjohnston  and @anshulkumar189 
I am also facing same issue. Have you got solution to this problem ?
Thank you :)
