### ISSUE TITLE
Spike: Ensure support for Swift 4.2 and Xcode 10

### ISSUE THREAD

**Issue by sorianog** [ProjectDent/ARKit-CoreLocation#134]
I'll take point on this. Thanks @aaronbrethorst @intere 💯

TODOs/Clear any:
- [x] Build errors
- [x] Warnings (i.e. deprecated methods)
- [x] Build settings
- [ ] Regression Testing

**Comment by intere** [comment]
@sorianog - no, that is only a problem if you're trying to ship to the app store.  That's definitely unfortunate, though.

> @aaronbrethorst @intere Does it matter to fix this warning:
> 
> `/Users/gerald/Documents/Development/Repos/MyForks/ARKit-CoreLocation/ARKit+CoreLocation/Assets.xcassets:-1: A 1024x1024 app store icon is required for iOS apps`

**Comment by sorianog** [comment]
@intere Sweet. Just submitted a PR. Would be awesome to have another person pull down my changes and test on their respective devices as well! I used a iPhone 6S Plus for testing. (Made sure not to commit any dev_team profile changes 😉)

**Comment by aaronbrethorst** [comment]
this is fixed.
