### ISSUE TITLE
ARCL lacks Continuous Integration (CI)

### ISSUE THREAD

**Issue by intere** [ProjectDent/ARKit-CoreLocation#136]
### Background
To help prevent the introduction of (at the very least) a baseline that doesn't compile and to help prevent regressions, we should setup some sort of CI.

### Suggestions
Let's setup fastlane + TravisCI.  It's cheap, and pretty easy.

**Comment by sorianog** [comment]
@aaronbrethorst Would love to help out @intere with this! What are your thoughts about moving forward with this?

**Comment by intere** [comment]
My thoughts were the following:
1. Add fastlane and a lane to compile / run the tests
2. Setup a `.travis.yml` file to run the tests and wire it up so PRs and the mainline are built whenever there are pushes.

**Comment by intere** [comment]
This has been addressed by: https://github.com/ProjectDent/ARKit-CoreLocation/pull/207
