### ISSUE TITLE
Allowing change change of lat and long of the current position (Relocation in AR)

### ISSUE THREAD

**Issue by amahajan87** [ProjectDent/ARKit-CoreLocation#139]
Currently  AR revolves around the current position (user location- Bowling Green, Ohio). 
I want to relocate myself to a new location (say Chicago, California, Phoenix)...
and try to see locations around me as if I am in that new relocated place virtually. 
This feature is not there yet. Could this feature be added to the current project. I am already using this library and would want to continue using it.

**Comment by intere** [comment]
@amahajan87 - I can see the relevance / use of this feature.  I'm not sure of the level of effort.
