### ISSUE TITLE
Remove all location node

### ISSUE THREAD

**Issue by TheCodeTalker** [ProjectDent/ARKit-CoreLocation#140]
i am trying remove all the  location node i am found only one way to remove that is one by one `removeLocationNode(locationNode: LocationNode)` . and its better to add to remove all also.

**Comment by aaronbrethorst** [comment]
Is there a reason that `removeAllNodes` isn't sufficient for your needs?

**Comment by TheCodeTalker** [comment]
I am using 1.0.4 pod version it's not available in that. Also it would be great if you could make SceneLocationView and LocationManager as **open** class, because we are trying to add few functionality on top of it.
