### ISSUE TITLE
Example with text as well as graphic

### ISSUE THREAD

**Issue by ChrisAldridgeRIT** [ProjectDent/ARKit-CoreLocation#141]
Do you have an example where the annotation is a graphic (eg speech bubble) with a text label on it? 
Thanks

**Comment by developerark** [comment]
![annotation](https://user-images.githubusercontent.com/23172754/50365221-20053e00-0539-11e9-9667-e5714937cc1c.jpg)

**Comment by developerark** [comment]
Here you go. 
This fork as a implementation for adding a Custom View and get notifications when the annotations are touched on the screen
https://github.com/developerark/ARKit-CoreLocation/tree/develop
Checkout the `develop` branch

**Comment by ChrisAldridgeRIT** [comment]
thats great thanks
