### ISSUE TITLE
Update Cocoapod

### ISSUE THREAD

**Issue by edmund-h** [ProjectDent/ARKit-CoreLocation#142]
Seems like some of the recent updates to master are not in the cocoapod. 

The example I have seen is the `coordinateWithBearing(bearing: , distanceMeters: )` method  in `CoreLocation+Extensions.swift` which has an additional 2.7 feet or 0.8m latitudinal accuracy at my location (should provide more accuracy at locations closer to the equator). I think it might provide longitudinal accuracy as well, but can't confirm. 

At any rate, this would be a "nice to have" for me personally but I'm wondering if other updates that are stable and beneficial aren't in the cocoapod. I posted in the slack channel about whether the cocoapod was up to date and was directed here to create an issue.

**Comment by aaronbrethorst** [comment]
1.1.0 was just tagged and pushed to cocoapods.
