### ISSUE TITLE
Moving Target

### ISSUE THREAD

**Issue by awesomeo99** [ProjectDent/ARKit-CoreLocation#144]
Is it possible to assign a tag on moving object? For example - if a friend and I are in a large crowded park then I can see his accurate location at all times as long as he has the "FIND ME" type feature turned on?

Kinda like this: 
https://mobile-ar.reality.news/news/apple-ar-quickly-find-your-friends-crowded-places-with-neon-app-0179493/

I have done this before in ARCore in Android but I am not sure if its possible with this repo in ARKit

Any feedback will be appreciated.

Thank you

**Comment by intere** [comment]
Yes, of course you can build this type of experience.  It's not a built in feature of the library, but you could certainly use this library to build an app that does that.
