### ISSUE TITLE
Pin annotation flickering sometimes in our application as well as GitHub demo app

### ISSUE THREAD

**Issue by manekdilip** [ProjectDent/ARKit-CoreLocation#146]
I'm trying to resolve flickering issue but did not get any proper solution,
Sometime annotation pin automatically go up , down or left , right,
Please help me to resolve this issue.

Thank you.

**Comment by stephanrueschenbaum** [comment]
I have the same issue. Maybe it affects only near by annotations?

**Comment by intere** [comment]
Although it is a bit janky, it's not an issue.  What's happening is that the scene is being updated because of changes to your location.  The "flicker" is the objects moving and being redrawn.  It's not ideal.  Perhaps you should come up with a solution and submit a pull request?
