### ISSUE TITLE
Setting background colour when using buildViewNode

### ISSUE THREAD

**Issue by elga2** [ProjectDent/ARKit-CoreLocation#154]
Using latest cut of master using buldViewNode. Setting background, text colour and corner radius. All of which appear ok apart from there appears to be a default white rectangle behind my coloured shape. Can someone please suggest a way of turning off the white rectangle?

**Comment by Sibaiur** [comment]
Did you find out how to remove the white background?

**Comment by Sibaiur** [comment]
Go to LocationNode.swift and into the constructor, add view.isOpaque = false.

 public init(location: CLLocation?, view: UIView){
        let plane = SCNPlane(width: view.frame.size.width / 100, height: view.frame.size.height / 100)
        plane.firstMaterial!.diffuse.contents = view
        plane.firstMaterial!.lightingModel = .constant
        **view.isOpaque = false**
        annotationNode = AnnotationNode(view: view, image: nil)
        annotationNode.geometry = plane

**Comment by developerark** [comment]
@elga2 You can set the view's isOpague property to false as @Sibaiur  mentioned. Instead of modifying the framework's constructor you can do it when you set your view in code.

**Comment by developerark** [comment]
@aaronbrethorst this is resolved
