### ISSUE TITLE
Click event on annotation node

### ISSUE THREAD

**Issue by yogendragirase55** [ProjectDent/ARKit-CoreLocation#161]
I am using following code to render annotations node - 
 
        public init(location: CLLocation?, view: UIView) {
   
        UIGraphicsBeginImageContextWithOptions(view.frame.size, false, UIScreen.main.scale);
        view.layer.render(in: UIGraphicsGetCurrentContext()!)
        let screenShot = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        let plane = SCNPlane(width: view.frame.size.width / 100, height: view.frame.size.height/100)
        plane.firstMaterial!.diffuse.contents = screenShot
        plane.firstMaterial!.lightingModel = .constant
        
        annotationNode = AnnotationNode(view: view, image: nil)
        annotationNode.geometry = plane
        super.init(location: location)
        let billboardConstraint = SCNBillboardConstraint()
        billboardConstraint.freeAxes = SCNBillboardAxis.Y
        constraints = [billboardConstraint]
        addChildNode(annotationNode)
    }

But the problem is its rendering image as annotation and I want some click events for particular portion on image. (My requirement is something like I am rendering a view and view contains buttons. I can tap on buttons to get the event) But in this case '**plane.firstMaterial!.diffuse.contents**' does not accept the view so I have to convert a view into image. Now when a view converts into image then I loose the button events as its an image now. 

Example:

I want to like this and how we can get button events methods 

![screenshot 2019-02-21 at 7 48 11 pm](https://user-images.githubusercontent.com/47450325/53175308-b1fcf600-3611-11e9-96e1-186456c4b163.png)

**Comment by developerark** [comment]
@yogendragirase55 Would it help if:
func locationNodeTouched(node: AnnotationNode) {
        // Do stuffs with the node instance
        
        // node could have either node.view or node.image
        if let nodeView = node.view{
            // Do stuffs with the nodeView
            // ...
        }
        if let nodeImage = node.image{
            // Do stuffs with the nodeImage
            // ...
        }
    }
also provided the location of touch in the sceneLocationView? That way you can use the tap location to see if the button was touched? If so, I can add the functionality soon.

**Comment by developerark** [comment]
> But in this case '**plane.firstMaterial!.diffuse.contents**' does not accept the view so I have to convert a view into image.

Use this to add a view. No need to convert to an image.
```swift
let coordinate = CLLocationCoordinate2D(latitude: 51.504571, longitude: -0.019717)
let location = CLLocation(coordinate: coordinate, altitude: 300)
let view = UIView() // or a custom UIView subclass

let annotationNode = LocationAnnotationNode(location: location, view: view)
```

**Comment by miaozaswdd** [comment]
i also cannot add view

**Comment by developerark** [comment]
> i also cannot add view

What issues do you get when adding a UIView? We have tested the constructor that takes UIView and it had worked properly.

**Comment by tz70s** [comment]
I've met issue on adding UIView as well by installing ARCL via cocoapods, but resolved this after manual installation. I guess it might be outdated and no relevant constructor for UIView.

**Comment by developerark** [comment]
@yogendragirase55 & @miaozaswdd Cocoapods installs the latest release which is tagged (1.0.4). Adding UIView was not available back then. If you want to use the functionality install it by source for right now as @tz70s mentioned. I will open another issue for creating a new release so it is available with Cocoapods.

**Comment by developerark** [comment]
@aaronbrethorst need to update Cocoapods. Will open a new issue. This is resolved

**Comment by yogendragirase55** [comment]
@developerark 

**When I use below code for show UIView :**
 ```
func buildViewNode(latitude: CLLocationDegrees, longitude: CLLocationDegrees,
                       altitude: CLLocationDistance, text: String) -> LocationAnnotationNode {
        let coordinate = CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
        let location = CLLocation(coordinate: coordinate, altitude: altitude)

        let uiview = UIView()
        uiview.frame = CGRect(x: 0, y: 0, width: 200, height: 200)
        uiview.backgroundColor = UIColor.red
        return LocationAnnotationNode(location: location, view: uiview)
    }
```
And go to another **SecondViewController** like that : 

 ```
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        super.touchesBegan(touches, with: event)
        let vc = UIStoryboard.init(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "SecondViewController") as? SecondViewController
                self.navigationController?.pushViewController(vc!, animated: true)
}
```
After push **SecondViewController** navigation back button not working and also I have added another UIButton click event not is working. It's means everything is freeze . 
Please check and let me know it is working on your side ?
If YES so please let me what is the solution .
Thanks

**Comment by samatzp** [comment]
@yogendragirase55 Hi! any solution for tap?
