### ISSUE TITLE
Delete _SCNSnapshotWindow after leaving Augmented Reality View

### ISSUE THREAD

**Issue by Sibaiur** [ProjectDent/ARKit-CoreLocation#162]
When leaving my Augmented Reality View Controller, there is these _SCNSnapshotWindow objects that still exists on the top left corner of my screen and prevent me from interacting with any objects beneath them, in my case its my return to main menu button. Anybody know how can I get rid of these objects?
![screen shot 2019-02-12 at 08 18 00](https://user-images.githubusercontent.com/9104526/53359511-32a04880-38d7-11e9-83f7-ef0be7baa8c8.png)

**Comment by intere** [comment]
@Sibaiur - this should be fixed in the following PR: https://github.com/ProjectDent/ARKit-CoreLocation/pull/176
