### ISSUE TITLE
Cocoapods update

### ISSUE THREAD

**Issue by developerark** [ProjectDent/ARKit-CoreLocation#163]
Lots of new functionalities have been added since the last release. May be its time for another release.

**Comment by intere** [comment]
@developerark - you're absolutely right!  I'm in the process of working on this, I'll have a PR for this soon.

**Comment by aaronbrethorst** [comment]
this is complete. you can now update to 1.1.0

**Comment by intere** [comment]
Release Notes: https://github.com/ProjectDent/ARKit-CoreLocation/releases/tag/1.1.0
