### ISSUE TITLE
Scaling of polyline node

### ISSUE THREAD

**Issue by bezoadam** [ProjectDent/ARKit-CoreLocation#167]
If you check SCNScene render in Debug View Hierarchy you can see that scaling of polyline nodes isn't working properly. From point of view it looks good but sometimes you can see that there is problem with nodes that are far away. Is possible to fix this somehow? Thanks
![snimka obrazovky 2019-03-08 o 14 10 30](https://user-images.githubusercontent.com/25613125/54030490-1096a800-41ac-11e9-8134-d85f60b908a8.png)

**Comment by intere** [comment]
Are you sure they're not being sized correctly and it's not just the perspective?

**Comment by Pilot-Marc** [comment]
[PR #209](https://github.com/ProjectDent/ARKit-CoreLocation/pull/209) fixes an issue where polyline scaling doesn't get updated when the bearing from the camera changes.  Might this fix your issue?

**Comment by intere** [comment]
@bezoadam - I'm closing this issue since @Pilot-Marc believes he's addressed this issue and this issue has been inactive for so long.
