### ISSUE TITLE
How can add Arrow for direaction

### ISSUE THREAD

**Issue by yogendragirase55** [ProjectDent/ARKit-CoreLocation#169]
Hi 
I have used the code for create navigation path but i need to implement red arrow show on top of navigation path.
How can implement ?

**Comment by intere** [comment]
Here's a link to an [arrow.scn](https://github.com/intere/GeoTrackKit/blob/4db8495f3169fc474c2ce8e0d65eb0b31cda604d/GeoTrackKitExample/GeoTrackKitExample/example.scnassets/arrow.scn) file that I built a while back.  You just drop it wherever you think is appropriate.
