### ISSUE TITLE
Custom SNCNode (exp: Cube )

### ISSUE THREAD

**Issue by muratyilmaz** [ProjectDent/ARKit-CoreLocation#170]
How can i custom SNCNode instead of LocationAnnotationNode? 
I derive LocationNode but i can not override updatePositionAndScale methood.

Any solution?

**Comment by intere** [comment]
Here's an [Example: ArrowLocationNode.swift](https://github.com/intere/GeoTrackKit/blob/4db8495f3169fc474c2ce8e0d65eb0b31cda604d/GeoTrackKitExample/GeoTrackKitExample/Views/ARCL/ArrowLocationNode.swift)

1. A factory creation function is called at [line 20](https://github.com/intere/GeoTrackKit/blob/4db8495f3169fc474c2ce8e0d65eb0b31cda604d/GeoTrackKitExample/GeoTrackKitExample/Views/ARCL/ArrowLocationNode.swift#L20)
2. A model is loaded from a scene file at [line 81](https://github.com/intere/GeoTrackKit/blob/4db8495f3169fc474c2ce8e0d65eb0b31cda604d/GeoTrackKitExample/GeoTrackKitExample/Views/ARCL/ArrowLocationNode.swift#L81) (but in reality, you can build your nodes programmatically if you want)
3. The model is then added as a child of the LocationNode at [line 26](https://github.com/intere/GeoTrackKit/blob/4db8495f3169fc474c2ce8e0d65eb0b31cda604d/GeoTrackKitExample/GeoTrackKitExample/Views/ARCL/ArrowLocationNode.swift#L26)

And Bob's your uncle!
