### ISSUE TITLE
Slack Invite not working

### ISSUE THREAD

**Issue by sutee9** [ProjectDent/ARKit-CoreLocation#172]
The Slack Invite on your github is not up to date. Would be great to get in on the community to discuss...

**Comment by yogendragirase55** [comment]
I have a same problem

**Comment by aaronbrethorst** [comment]
Thanks for the report. Fixed. https://join.slack.com/t/arcl-dev/shared_invite/enQtNTk4OTg4MzU0MTEyLTMzYTM0Mjk0YmNkMjgwYzg4OWQ1NDFjNjc3NjM1NzdkNWNkZTc2NjQ1MWFiNmI1MTZiMTA5MmNjZmRiOTk1NjI
