### ISSUE TITLE
How do I move to the development branch?

### ISSUE THREAD

**Issue by joeuelk** [ProjectDent/ARKit-CoreLocation#190]
I'm on ARCL (1.1.0) right now via cocopods.

I saw that there is a [fix](https://github.com/ProjectDent/ARKit-CoreLocation/pull/176) for this [touch problem](https://github.com/ProjectDent/ARKit-CoreLocation/issues/164) but it's not available in 1.1.0.

What's the best way to move to the latest and greatest?

Thank you!

**Comment by intere** [comment]
Try 1.2.0 - just released today: https://github.com/ProjectDent/ARKit-CoreLocation/releases/tag/1.2.0

**Comment by JacoGasp** [comment]
> Try 1.2.0 - just released today: https://github.com/ProjectDent/ARKit-CoreLocation/releases/tag/1.2.0

Hey @intere, 
sorry but I'm trying the release 1.2.0 but I'm receiving the compiling error "Use of undeclared type 'ScalingScheme'". How can I solve it?

**Comment by joeuelk** [comment]
Great update. Thanks
