### ISSUE TITLE
Delegate issue when assigned to self

### ISSUE THREAD

**Issue by Jmats17** [ProjectDent/ARKit-CoreLocation#196]
Had an issue in my viewDidLoad where I accidentally set the sceneView delegate to self. Resulted in my not being able to view the added nodes or make use of the touch function. After removing that line of code, all worked fine again

**Comment by intere** [comment]
@Jmats17 - PR to address this is in review: https://github.com/ProjectDent/ARKit-CoreLocation/pull/206

**Comment by intere** [comment]
@Jmats17 - I'm closing this issue since that PR was merged in.
