### ISSUE TITLE
Details of touched node

### ISSUE THREAD

**Issue by perunworks** [ProjectDent/ARKit-CoreLocation#214]
Is there a way to get the details of a node I clicked when I'm in "locationNodeTouched", like the lat, long, and the text of the node?

**Comment by developerark** [comment]
### Overview
Few things you need to know:
1. `LocationAnnotationNode` has a `location` property (derived from `LocationNode`) that gets set when you use either `LocationAnnotationNode(location: CLLocation, image: UIImage)` or `LocationAnnotationNode(location: CLLocation, view: UIView)` constructor.
2. `LocationAnnotationNode` has a `annotationNode` property

When `locationNodeTouched(node: AnnotationNode)` delegate method reports back with a `node`, it is the same `annotationNode` that is a property of `LocationAnnotationNode` that you created before adding it to an instance of `SceneLocationView`. 

### Getting Location 
At the moment, there is no way of getting location info from `AnnotationNode` instance. One thing you can do is maintain a hash table that maps [AnnotationNode: CLLocation] and update it at the time of adding `LocationAnnotationNode` to the `SceneLocationView`. Then when the delegate method `locationNodeTouched(node: AnnotationNode)` reports back with a `node`, you can look up the location in the hash table. 

### Getting text
If you are using the master branch, there is a way to get/change the text of the `AnnotationNode` if you used a `UIView` to initialize it. However, there is a commit bdf0b1d2d52ae4210b02d50d3531c38a0e18f2ec on the develop branch by @intere that gets rid of the functionality that allowed having `UIView` in the `AnnotationNode`. Instead the new implementation turns the `UIView` instance into a `UIImage` instance and freezes the content.

**Comment by developerark** [comment]
@intere Can probably close this out. But based on other pull requests #219 (video as a node) it will be great to be able use a UIView in the LocationAnnotationNode as before.
