### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by intere** [ProjectDent/ARKit-CoreLocation#218]

**Comment by Pilot-Marc** [comment]
Did I forget to merge something?  Apologies.

**Comment by intere** [comment]
@Pilot-Marc - no you didn't do anything wrong.  The ask is to take all the stuff we've merged into `deveop` and release it.  I just need to go through the release process.  You're the reason I'm able to do a release with all of the good stuff you've contributed!  Thanks for your hard work!

**Comment by intere** [comment]
This has been released: https://github.com/ProjectDent/ARKit-CoreLocation/releases/tag/1.2.1
