### ISSUE TITLE
renderer(_:didAdd:for:) Not getting called

### ISSUE THREAD

**Issue by furzik** [ProjectDent/ARKit-CoreLocation#226]
Hello, I have set the tracking as `.worldTracking`, set the `arViewDelegate` to self, conforming to `ARSCNViewDelegate`, but I am not getting the callback for a new plane anchor. All I see getting triggered is `renderer(_: nodeFor)` getting called. When I switch it to use a vanilla `ARSCNView` I get a new anchor almost instantly. Am I missing something? 
Also, thanks for the great library!

**Comment by furzik** [comment]
Nevermind... if you provide `renderer(_: nodeFor)` with a node to add to the anchor then it'll call `renderer(_:didAdd:for:)` 🤦‍♂️. I suppose your implementation just doesn't create an empty node by default like the parent does.

**Comment by halmueller** [comment]
That seems worth clarifying in the doc/comments. Who is “you”? The calling application?

Hal
