### ISSUE TITLE
I am unable to modify the image of a node

### ISSUE THREAD

**Issue by f6qpQNBA3p** [ProjectDent/ARKit-CoreLocation#227]
Hello,
I add LocationAnnotationNode, then I loop through sceneLocationView.locationNodes, and then when I try : 
`if let locationAnnotationNode = locationNode as? AnnotationNode
                                                    {
                                                        locationAnnotationNode.image = newImage
                                                    }`
I get this warning : **Cast from 'LocationNode' to unrelated type 'AnnotationNode' always fails**

Does someone can help me to change the image please ?

**Comment by JacoGasp** [comment]
I think you should cast the `locationNode` as `LocationAnnotationNode` or a subclass of it.

Doing this
```swift
for locationNode in sceneLocationView.locationNodes {
    if let locationAnnotationNode = locationNode as? LocationAnnotationNode {
        locationAnnotationNode = #imageLiteral(resourceName: "WikiIcon")
        }
    }
```
I don't receive warnings.
But I don't think you can simply change the annotation image because the SCNode is build during the `init`, thus probably you have to destroy/rebuild the nodes (not 100% sure about this)

**Comment by f6qpQNBA3p** [comment]
> I think you should cast the `locationNode` as `LocationAnnotationNode` or a subclass of it.
> 
> Doing this
> 
> ```swift
> for locationNode in sceneLocationView.locationNodes {
>     if let locationAnnotationNode = locationNode as? LocationAnnotationNode {
>         locationAnnotationNode.annotation.image = #imageLiteral(resourceName: "WikiIcon")
>         }
>     }
> ```
> 
> I don't receive warnings.
> But I don't think you can simply change the annotation image because the SCNode is build during the `init`, thus probably you have to destroy/rebuild the nodes (not 100% sure about this)

Thank you very much !
I also think that I will not be able to change the image, I can't try now but I hope that it will work, I close the issue and will try to remember to add a message to say if it worked.
PS: just for information, I had to write locationAnnotationNode.annotationNode instead of locationAnnotationNode.annotation

Thanks again :) :) :)

**Comment by halmueller** [comment]
Using a live SpriteKit scene as the material of your SceneKit node might be a solution. I’ve used this approach for pure SceneKit problems but haven’t tried it with ARKit yet.

Hal
