### ISSUE TITLE
Creating polylines from the view controller's viewDidLoad

### ISSUE THREAD

**Issue by DerekK19** [ProjectDent/ARKit-CoreLocation#234]
I have a scene that includes a number of location nodes (these are sailing marker buoys) and I want a polyline, which is the course to be followed around the buoys. There are a number of problems with this:
- I create my nodes in my viewDidLoad procedure and at that time I don't have an altitude, so addPolylines aborts.
- At this point there is no sceneNode in the SceneLocationView, so even If I get round the altitude issue (basically defaulting my altitude to 0 rather than aborting) the polyline nodes don't get added to the scene.

I have code that resolves these issues, which I would pull request, but am I misusing polylines at all? Are they really intended for a route that's placed on an existing scene (e.g a route from where I am to a distant node)

**Comment by halmueller** [comment]
I think the mistake is adding nodes when you don’t know the location yet. That will force the lat/lon to x/y conversion to fail. See the demo app, which requeues the node add request until there’s a good location. 

Hal Mueller 
halmueller@gmail.com

**Comment by DerekK19** [comment]
Hi Hal  

Thanks for that tip. I’ve just looked at your demo app and see what you’re doing in your addSceneModels function. I’ll give that a go tomorrow. Also you could probably close your issue about Carthage if that’s now resolved  

Derek

--  
Derek Knight
