### ISSUE TITLE
Is it possible to do point of interest in simulated 360 view?

### ISSUE THREAD

**Issue by lazyprogram** [ProjectDent/ARKit-CoreLocation#238]
I am trying to show the point of interest in 360 image. Is it possible to do this using this library?

**Comment by halmueller** [comment]
I'm not sure what you're asking for. I think that you could use it for that purpose but you'd need to make substantial modifications. The Location Manager works on current device location, so you'd have to modify that. And the SceneLocationView relies on real world tracking, so you'd have to override that. The core functionality you'd be using is the conversion of lat/lon/elevation to SceneKit style x/y/z, but I don't know how cleanly that is exposed.
