### ISSUE TITLE
POIViewController Memory Leak

### ISSUE THREAD

**Issue by Pilot-Marc** [ProjectDent/ARKit-CoreLocation#248]
Backing out of POIViewController does not dealloc all it's properties.  Image below shows memory footprint fo the app growing at each invocation of the POIViewController.  I suspect the root of the problem is in the SceneLocationManger, but haven't found the property (or properties) that don't autorelease correctly.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/12265773/69482216-0241f800-0dde-11ea-9b7f-4a2e3598873a.png">

**Comment by halmueller** [comment]
Looks like `updateUserLocationTimer` and `updateInfoLabelTimer` each keep strong references to the view controller. Those will persist unless they're invalidated.

**Comment by Pilot-Marc** [comment]
Yes, those are already fixed in my local repo, along with a third timer in SceneLocationManger.  Besides these strong references, there's one more somewhere in SceneLocationView that I need to track down.

**Comment by Pilot-Marc** [comment]
Fixed.  Here's the memory graph after 1 invocation of POIViewController.  Possibly some room for additional improvement (?), but it's significantly better.  PR coming momentarily.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/12265773/69488956-1b2ac780-0e37-11ea-94a7-5970f14f7422.png">

**Comment by Pilot-Marc** [comment]
Closing this issue with the approval of PR 249
