### ISSUE TITLE
Draw a line from bottom screen to node ?

### ISSUE THREAD

**Issue by ghost** [ProjectDent/ARKit-CoreLocation#260]
Hello, I am trying to draw a line from the bottom screen to a node, without success.
Can someone help me ?

**Comment by Pilot-Marc** [comment]
Your issue description above is a bit vague.  Is the line such that the bottom is anchored to a fixed screen coordinate while the other end is affixed to a node with CLLocation coordinates that moves as the camera angle and position changes?  Possibly mocking up a PNG with what you're hoping to accomplish might help too.

**Comment by ghost** [comment]
> Your issue description above is a bit vague. Is the line such that the bottom is anchored to a fixed screen coordinate while the other end is affixed to a node with CLLocation coordinates that moves as the camera angle and position changes? Possibly mocking up a PNG with what you're hoping to accomplish might help too.

Yes I think we understood each other :)
Here is exactly the type of line that I am trying to do : 
![lines](https://user-images.githubusercontent.com/55389708/69977804-bdc80200-152b-11ea-8648-b13433aae37d.jpg)
Do you know if it would it be very hard to do ?
Any suggestions are welcome.

**Comment by halmueller** [comment]
You can do this with basic SceneKit primitives. I suggest using SCNBox or SCNCylinder. https://stackoverflow.com/questions/21886224/drawing-a-line-between-two-points-using-scenekit has some suggestions. You'll have to manage the position of the line yourself, animating its position when the squares' positions change, if you want a rubberband effect.
