### ISSUE TITLE
Shapefile instead of Direction 

### ISSUE THREAD

**Issue by sp062** [ProjectDent/ARKit-CoreLocation#267]
How to use shapefile instead of direction to get line on map and camera?

**Comment by halmueller** [comment]
Parse the shapefile into points or lines (or polygons), and create LocationNode instances with SCNGeometry-based nodes (probably SCNBox for lines, some other geometry for points, and perhaps an extruded shape for polygons) as children.

**Comment by sp062** [comment]
any example code

**Comment by halmueller** [comment]
Where are you getting stuck?

Can you open, read, and parse a shapefile?

Do you know how to create a SceneKit node using a standard SCNGeometry? How to create an extruded node?

Do you know how to add a child node to a LocationNode?

**Comment by sp062** [comment]
stuck in how to open, read, and parse a shapefile.

**Comment by halmueller** [comment]
You'll have better luck getting an answer there by posting code snippets to StackOverflow. There's nothing about that that's particular to ARCL. When I Google "how do i parse a shapefile in swift" I find several Github projects, the actual Shapefile spec, the reference Shapelib in C, and many other resources. You might be happier, though, using GDAL/OGR to convert your shape files into GeoJSON, which is easier to work with in Swift than the low-level C constructs.

**Comment by sp062** [comment]
I got shapfile to GeoJSON data and how to use this to create a SceneKit node using a standard SCNGeometry

**Comment by halmueller** [comment]
This is a SceneKit question, not an ARKit or ARCL question. Post your code to StackOverflow, tag it with SceneKit, send me the URL to the question, and I’ll take a look.

**Comment by sp062** [comment]
https://stackoverflow.com/questions/59836716/from-geojson-data-how-to-create-a-scenekit-node-using-a-standard-scngeometry
