### ISSUE TITLE
Polyline nodes not being added to sceneLocationView

### ISSUE THREAD

**Issue by Un1xG0d** [ProjectDent/ARKit-CoreLocation#285]
Hi, when working on my own project, and even testing an unmodified version of the latest code, the 3D polyline is not added to the AR scene, and I'm having a hard time debugging this. I have added several print statements to ensure that the addRoutes/addPolylines functions are reached successfully, and the print statements fire every time.

The problem I'm facing is that the 3D line doesnt appear.

I've added the following print statements in the addPolylines function:
`print("added polyline node at \($0.location.coordinate)")`
`print($0.position)`
right after the node _supposedly_ gets added to sceneNode in this line: `sceneNode?.addChildNode($0)`

The latlong and xyz coordinates are printed into the console and they look like values I'm expecting.

I tried using `print(sceneNode?.childNodes)` and `print(sceneNode)` to view the nodes that were supposed to be added to the scene, but these both come back as `nil`. Several functions say they will silently fail if sceneNode is nil, but I cant seem to figure out why the nodes arent getting added. Has anyone seen this bug before?

**Comment by halmueller** [comment]
sceneNode?.addChildNode($0)will fail if sceneNode is nil. There’s no parent node to add the child to. The error is likely in your setup code before the call to addChildNode.

Useful idioms here would be something like an if-let, a guard-else, or guard let-else. By failing silently, ARCL is allowing your program to not crash, but it’s a logic error in your client code to add a child to a nil node.

**Comment by Un1xG0d** [comment]
Where specifically does sceneNode get initialized?

**Comment by halmueller** [comment]
I was going to ask YOU that. You’re the one passing the variable :)

Do a command-click on `sceneNode` and it will show you the definition that you’ve give it.

**Comment by Un1xG0d** [comment]
It starts on line 86 of SceneLocationView. This file was pulled from the `develop` branch and has been unmodified, which is why I'm getting a little confused as to how/why it is nil.

https://github.com/ProjectDent/ARKit-CoreLocation/blob/3096c440e12da642bcf95f585a53ab316e190241/Sources/ARKit-CoreLocation/SceneLocationView.swift#L86

**Comment by halmueller** [comment]
At this point it’s looking to me like a debugging problem, not an ARCL bug. If you can post a minimal repro with code I’ll take a look, though. I need to see the code leading up to where you grab `sceneNode`.

**Comment by Un1xG0d** [comment]
I think I narrowed down where the issue may lie, but I need to do some more digging. It looks like didRenderScene is called _after_ the nodes get added, whereas the demo code completes rendering _before_ the loop in addPolylines gets called. I'll close this issue out since it is not a bug with ARCL. Thanks so much for your help!
