### ISSUE TITLE
Crash on [ARSCNView _removeAnchors] - C3DNodeRemoveFromParentNode BAD_ACCESS

### ISSUE THREAD

**Issue by michaelcolville** [ProjectDent/ARKit-CoreLocation#29]
The app crashes if you move some distance away from your starting location.

It seems to happen when ARKit removes a plane anchor, and removing this line `configuration.planeDetection = .horizontal` resolves the issue.

Full crash attached

[crash.txt](https://github.com/ProjectDent/ARKit-CoreLocation/files/1245056/crash.txt)

**Comment by ProjectDent** [comment]
I haven't personally experienced this but have heard numerous reports about it. I'd be open to removing the planeDetection setting, so long as there won't be any adverse side effects.. but then that wouldn't resolve it for those who require that for their projects. This does sound like an Apple bug though - the library itself never actually attempts to remove anchors.

**Comment by isavinskyi** [comment]
Same here. Have anybody solved this issue?
Any updates from Apple about filled bug?
