### ISSUE TITLE
Store and retrieve additional info/property in LocationAnnotationNode

### ISSUE THREAD

**Issue by gp-wang** [ProjectDent/ARKit-CoreLocation#32]
I need to store additional information inside an LocationAnnotationNode. So I subclassed LocationAnnotationNode as MyLocationAnnotationNode, with an additional property called id. 

Later when I did a hit test in sceneLocationVIew's touchBegan, I wasn't able to retrieve the additional id property, because the hit-result's SCNNode is not convertible to MyLocationAnnotationNode.

I tried another way by setting the SCNNode.name before adding them to sceneLocationView. However, when I do a hit test, the name info becomes nil.

What is the recommended way to store information in pins in the scene, and retrieve them later in hit test?

**Comment by mattcianna** [comment]
I'm having the same issue. I can't get the node properties in the touchesBegan method.

**Comment by Awalz** [comment]
I got this to work using the hit-results. The trick is the node returned from hit-results is not the `LocationAnnotationNode`, but rather a child `SCNNode`. To the get the `LocationAnnotationNode`:
        for result in hitResults {
            if let pin = result.node.parent as? LocationAnnotationNode {
                print(pin.location)
            }
        }

**Comment by mattcianna** [comment]
Thank you!
