### ISSUE TITLE
No such module `ARCL`

### ISSUE THREAD

**Issue by AbrahamArun** [ProjectDent/ARKit-CoreLocation#34]
After following the steps mentioned in the `setup using cocoapods`, I get the following error.

![screen shot 2017-08-30 at 9 53 08 am](https://user-images.githubusercontent.com/5391059/29855383-19cea22c-8d69-11e7-97da-5e7d0861deb1.png)

What could be wrong?

**Comment by skram** [comment]
Make sure you're opening the the project via .xcworkspace and not the .xcodeproj

**Comment by AbrahamArun** [comment]
Ah. Thank you very much
