### ISSUE TITLE
unable to see annotationNode after adding

### ISSUE THREAD

**Issue by AbrahamArun** [ProjectDent/ARKit-CoreLocation#35]
![screen shot 2017-08-30 at 5 48 34 pm](https://user-images.githubusercontent.com/5391059/29872021-7fdbb7d4-8dab-11e7-9658-b4cafee690b1.png)

I'm trying to do a basic example ^ where I would like to place a pin on a hardcoded co-ordinate near to me. This does not seem to work, any idea what could be wrong?

**Comment by ProjectDent** [comment]
First, I'd say you should put the code for placing the pin within `viewDidLoad` or another function that doesn't get called repeatedly, otherwise it'll be repeatedly added.

I think your issue here may be the altitude. If you look up, can you see it hovering in the sky? Try setting the altitude either to 0, or to your `currentLocation`'s altitude.

**Comment by AbrahamArun** [comment]
@ProjectDent  I could not find them hovering in sky and also at different altitudes. 

> your currentLocation's altitude

This ^ I have to get using CoreLocation, right?

**Comment by AbrahamArun** [comment]
@ProjectDent Got it, altitude was the problem. I used `currentLocation`'s altitude.

**Comment by Jatapiaro** [comment]
It is not working for me:

`import UIKit
import ARCL
import CoreLocation

class ViewController: UIViewController {
    
    var sceneLocationView = SceneLocationView()
    var currentLocation: CLLocation!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        sceneLocationView.run()
        
        let locationManager = CLLocationManager();
        if( CLLocationManager.authorizationStatus() == .authorizedWhenInUse){
            currentLocation = locationManager.location
        }
        
        print("Altitude", currentLocation.altitude);
        
        let coordinate = CLLocationCoordinate2D(latitude: currentLocation.coordinate.latitude, longitude: currentLocation.coordinate.longitude)
        let location = CLLocation(coordinate: coordinate, altitude: currentLocation.altitude)
        let image = UIImage(named: "pin")!
        
        let annotationNode = LocationAnnotationNode(location: location, image: image)
        sceneLocationView.addLocationNodeForCurrentPosition(locationNode: annotationNode)
        
        view.addSubview(sceneLocationView)
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        sceneLocationView.frame = view.bounds
    }

}
`
