### ISSUE TITLE
 sceneLocationView drastically slows down after a while (after about 30 sec)

### ISSUE THREAD

**Issue by gp-wang** [ProjectDent/ARKit-CoreLocation#36]
I have an application which adds about 10 pins/location nodes in the scene location view.

When the application first starts, the responsiveness is good, at about 60 FPS.
When the user started moving and after about 30 sec, the FPS steadily drops to about 5 fps and won't restore.

**Comment by ProjectDent** [comment]
Could you give any details on what those location nodes are? How many lights are being added to the scene? If you were to modify the `updatePositionAndScaleOfLocationNodes` to only be called every 2 seconds, for example, does that improve performance?

**Comment by gp-wang** [comment]
These pins are added as confirmed location nodes (they are created with confirmed lat/lon).

I used the default lighting (.constant) for each pin.

I have tried to change the update timer interval to 2sec, but no luck, it still slows down after about 30 sec.

I am using iphone 6s

**Comment by gp-wang** [comment]
This is fixed on an unrelated location

**Comment by JacoGasp** [comment]
Hi @gp-wang,
could you explain a little better because I'm facing with the same problem? thanks

**Comment by Undo1** [comment]
Same issue here, on a 6S. Only a few pins (images, just like the demo) and it slows down seemingly on its own.

**Comment by scm573** [comment]
I'm facing the same problem. What I'm doing is just calling "addLocationNodeWithConfirmedLocation()" with several locations and images.
Any suggestions would be great appreciated.
