### ISSUE TITLE
Limit usage to newer devices

### ISSUE THREAD

**Issue by ProjectDent** [ProjectDent/ARKit-CoreLocation#37]
1. Add it to the readme that this should be limited to newer devices.
2. Add that limit to the sample app.

**Comment by chriswebb09** [comment]
Just to clarify, you mean restricting it to devices that can run iOS 11?

**Comment by hrishidev** [comment]
As Per [ARKit Documentation](https://developer.apple.com/documentation/arkit), it requires an iOS device with an A9 or later processor.

**Comment by evanfreeze** [comment]
> **Important**: If your app requires ARKit for its core functionality, use the **arkit** key in the UIRequiredDeviceCapabilities section of your app’s Info.plist file to make your app available only on devices that support ARKit. If AR is a secondary feature of your app, use the **isSupported** property to determine whether to offer AR-based features.  [(source)](https://developer.apple.com/documentation/arkit)

Seems like the isSupported way would be the most flexible since someone might using this for a secondary feature or mode in an app instead of the entire app. This would give older devices the ability to still run non-AR functions of an app that uses this.

**Comment by linox** [comment]
Hello people, how are you? Without a doubt, it is an excellent library, thank you for sharing with the community, I am new to AR development, and I am amazed at the possibilities.

So, I'm trying to include several location points, but I did not have success, could give me some help, right now, thank you.
