### ISSUE TITLE
Add custom coordinates instead of current position

### ISSUE THREAD

**Issue by owoshch** [ProjectDent/ARKit-CoreLocation#40]
In demo-app new points occur at your current position while tapping on the screen. I can find lines in code responsible for this.
I want to change the current location while tapping for another location and don't understand which variables are responsible for this
Do anybody know how to solve this issue?

**Comment by vihanb** [comment]
the lines you are looking for are here: https://github.com/ProjectDent/ARKit-CoreLocation/blob/master/ARKit%2BCoreLocation/ViewController.swift#L236 you can then pass a location to `LocationAnnotationNode(location:image:)` and change `addLocationNodeForCurrentPosition` to `addLocationNodeWithConfirmedLocation`

**Comment by owoshch** [comment]
Thank you so much!
