### ISSUE TITLE
Accessing Library from Objective c project

### ISSUE THREAD

**Issue by NyeinEiEiTun** [ProjectDent/ARKit-CoreLocation#41]
I would like to access this library from my objective c project. Is there a way to do that? pls hep me :)

**Comment by vihanb** [comment]
If you add the library a bridging header _should_ automatically be generated. I believe `#import "ARCL-Swift.h"` should work. I'm not sure if `@objc` tags need to be added though

**Comment by NyeinEiEiTun** [comment]
@thanks I will try this when I integrate this library to my current objective c project.

**Comment by vishal07malvi** [comment]
@NyeinEiEiTun  have you interegate this library in objective c project ?
