### ISSUE TITLE
Add multiple Objects/ Coordinates / pinCoordinate ?

### ISSUE THREAD

**Issue by entttom** [ProjectDent/ARKit-CoreLocation#45]
Hey,

i cant handle to insert multiple objects as in the demo GIF like Canary Wharf, O2 Arena, City of London etc.
How did you do that?

Best regards,
Thomas

**Comment by ZenunVee** [comment]
Hey, so I had multiple objects I added by using a for each loop. Check out my code, though yours may differ:

`cords.forEach { (cord) in
            
            let location = CLLocation(coordinate: cord, altitude: 60)
            
            let distance = location.distance(from: loc!)
            
            //804 is in meters - equal to half a mile
            if distance <= 804 {
                let annotationNode = LocationAnnotationNode(location: location, image: image)
                sceneLocationView.addLocationNodeWithConfirmedLocation(locationNode: annotationNode)
            }

        }`
