### ISSUE TITLE
cannot look around the whole 3D Objects when I tried to add 3D object as a node in sceneLocationView.

### ISSUE THREAD

**Issue by NyeinEiEiTun** [ProjectDent/ARKit-CoreLocation#47]
Instead of adding normal image, I tried to add 3D object as a location node in sceneLocationView. I can add and show the 3D object in the place of destination pin. But I could not look around that 3D object by rotating the camera of sceneLocationView. Can anyone explain me for this? I was stuck in this place. Thanks.

**Comment by Nayk0** [comment]
if you mean that you only see the object from one side, check if you have a lookAt constraint on that node

**Comment by NyeinEiEiTun** [comment]
Thanks for your replies. What I mean is in the 3D object we should able to see all the surfaces of object from various dimension. But for now I cannot see that.

**Comment by ProjectDent** [comment]
You should rotate the node using its' `eulerAngles` in order to see it from a different angle.
