### ISSUE TITLE
Still error while using Cocoapods!

### ISSUE THREAD

**Issue by WillRRRR** [ProjectDent/ARKit-CoreLocation#5]
Get error before using Cocoapods! Then, Still error while using Cocoapods!

<img width="1169" alt="screen shot 2017-07-28 at 4 40 26 pm" src="https://user-images.githubusercontent.com/30376565/28737327-9c639b2c-73b3-11e7-8b73-6c0e73e38e78.png">

**Comment by acroutworst** [comment]
I am getting the same error! I'm using Xcode 9 beta 3. It doesn't seem to be recognizing CocoaLumberJack 

<img width="920" alt="screenshot 2017-07-28 14 45 13" src="https://user-images.githubusercontent.com/10387238/28737460-7791f88a-73a3-11e7-8aee-9d91c0e2abbb.png">

**Comment by WillRRRR** [comment]
I already using Xcode 9 Beta 4

**Comment by ghecho** [comment]
Works fine for me in Xcode beta 4. Did you opened the workspace instead of the project?

**Comment by ghecho** [comment]
Just to clarify, I cloned the repo directly and then opened the Xcode workspace

**Comment by WillRRRR** [comment]
Fixed it

**Comment by ghecho** [comment]
Great
