### ISSUE TITLE
Custom UIView instead UIImage for LocationAnnotationNode

### ISSUE THREAD

**Issue by JacoGasp** [ProjectDent/ARKit-CoreLocation#50]
Hi,
I discovered this amazing library and I was wondering if it is possible to use custom UIViews, including UILabel etc, instead of a UIImage.
Is it necessary to convert the UIView to a UIImage or are there better ways to achieve that?

Thanks

**Comment by mpatzer** [comment]
+1. I like the example gif in the README. Is that done by creating the annotation-style views and then making into an image?

**Comment by vihanb** [comment]
I have a PR at #51 which will allow you to use a UIView rasterized or not. It’s not merged but you can use with:

```
pod 'ARCL', :git => 'https://github.com/vihanb/ARKit-CoreLocation.git', :commit => 'ff3cec0b33aec688a5d796ef25a71a6ea6517ddc'
```

**Comment by ddbien** [comment]
How to use this? please help me. Thanks.

**Comment by iain17** [comment]
@ddbien check the PR. a new initializer was added where you can supply a UIView instead of before just a UIImage.

https://github.com/ProjectDent/ARKit-CoreLocation/pull/51/files#diff-6defbf8fd2a6dee9baed204cd5fcdfcbR83

**Comment by ddbien** [comment]
Hi All,
How to customize location view same as attachment [file?](url) I try add view to LocationAnnotationNode but subview of view doesn't show.
<img width="219" alt="screen shot 2017-12-08 at 09 56 41" src="https://user-images.githubusercontent.com/4480119/33749090-96133cd8-dbfe-11e7-96b5-0e3fe5ffcc02.png">
