### ISSUE TITLE
Get all LocationAnnotationNode in SceneLocationView

### ISSUE THREAD

**Issue by hassanmah** [ProjectDent/ARKit-CoreLocation#52]
Hi,

Is it possible to get all `LocationAnnotationNode` in the `SceneLocationView`?

Thanks

**Comment by vihanb** [comment]
you can use `sceneLocationView.locationNodes`

**Comment by hassanmah** [comment]
@vihanb I see you can get sceneLocationView.locationNodes that are of type LocationNode, but I want the LocationAnnotationNode

**Comment by ProjectDent** [comment]
You can loop through the array and do `if let locationAnnotationNode = locationNode as? LocationAnnotation Node`
