### ISSUE TITLE
SceneLocationView variable access control 

### ISSUE THREAD

**Issue by antonwintergerst** [ProjectDent/ARKit-CoreLocation#53]
Receiving these errors when trying to run the demo code from a new project with ARCL added as a Pod dependency:
> 'showFeaturePoints' is inaccessible due to 'internal' protection level
> 'bestLocationEstimate' is inaccessible due to 'internal' protection level
> 'locationManager' is inaccessible due to 'internal' protection level

**Comment by antonwintergerst** [comment]
Pull request submitted: #54

**Comment by ProjectDent** [comment]
Commented on the PR (and closed it).
