### ISSUE TITLE
Altitude offset when adding bigger image

### ISSUE THREAD

**Issue by entttom** [ProjectDent/ARKit-CoreLocation#55]
Hey,

someone else experienced the altitude offset when you add a bigger image by "addLocationNodeWithConfirmedLocation" than 100 x 100?
How to get rid of that?
I attached some screenshot so you know what i mean:
First picture image size 50x50, 200x50, 400x50, 800x50
Best regards,
Thomas

![img_0086](https://user-images.githubusercontent.com/16444099/31134569-baf4cbd6-a862-11e7-9c02-7198098a8721.jpg)
![img_0087](https://user-images.githubusercontent.com/16444099/31134571-bb2378f0-a862-11e7-9068-c788a685ac81.jpg)
![img_0088](https://user-images.githubusercontent.com/16444099/31134570-bafb4254-a862-11e7-82cc-fe0cee7cb51a.jpg)
![img_0089](https://user-images.githubusercontent.com/16444099/31134568-baf4ca6e-a862-11e7-8193-b94300a4fbfa.jpg)

**Comment by intere** [comment]
Closing this issue - it's old and stale.
