### ISSUE TITLE
Scale Relative to distance hides the annotations

### ISSUE THREAD

**Issue by azamsharp** [ProjectDent/ARKit-CoreLocation#56]
When   self.scaleRelativeToDistance = true  then no annotations are displayed at all. Any ideas?

**Comment by yadavanand** [comment]
@azamsharp You need to implement SceneLocationViewDelegate methods

**Comment by navjotbola** [comment]
Hello, were you able to solve this? When I set a LocationAnnotationNode's scaleRelativeToDistance to true, the annotations are not displayed. I have these functions implemented:

sceneLocationViewDidAddSceneLocationEstimate, sceneLocationViewDidRemoveSceneLocationEstimate, sceneLocationViewDidConfirmLocationOfNode,
sceneLocationViewDidSetupSceneNode, and
sceneLocationViewDidUpdateLocationAndScaleOfLocationNode

**Comment by marcshilling** [comment]
It probably _is_ displaying them, just scaled very small so that you can't see them. It's very sensitive. Try plotting a node very close to your location.

**Comment by sungjin0213** [comment]
@azamsharp as @marcshilling said, it might appear really tiny if you enable scaleRealtiveToDistance since the library doesn't apply adjustment to make the node bigger. Try adding some scale to annotationNode to make it bigger to see if you can see them.

**Comment by miaozaswdd** [comment]
it is too small

**Comment by intere** [comment]
Closing this issue - it's old and stale.

**Comment by parajulizRoman** [comment]
I am willing to change the scale relative to distance boolean value based on users selection on segmented control. To provide user flexibility of selecting the modes 1. To view distant landmarks and 2. To view nearby landmarks scaled relative to the user's current location. HOW CAN I DO THAT?
