### ISSUE TITLE
Equivalent concepts in ARCore?

### ISSUE THREAD

**Issue by mickdee** [ProjectDent/ARKit-CoreLocation#61]
Not related to this repo, but figured I might get some guidance here --  Is there any equivalent technique for placing AR objects on lat / lon coordinates in ARCore? I'm hoping to experiment with this concept but have an Android device.

**Comment by MattSich** [comment]
Please join our slack channel for these kinds of questions =)

**Comment by hvmien** [comment]
@MattSich  How to jọin your slack channel? let me join! thanks.

**Comment by mulukalaabhisek** [comment]
Can you please mention the slack channel? I need some guidance on implementing the lat/lon distance calculations using AR Core.

**Comment by mulukalaabhisek** [comment]
^^^^@MattSich @mickdee

**Comment by mulukalaabhisek** [comment]
@ProjectDent
