### ISSUE TITLE
Location Issue 

### ISSUE THREAD

**Issue by JeKomme** [ProjectDent/ARKit-CoreLocation#63]
Hello there! thanks for the awesome lib, u rock guys!

I'm having an issue with locations as no matter what coordinates I'm using, the object always gets projected in my current location. How can I add/project my object to custom coordinates? 
![screen shot 2017-10-25 at 1 10 30 pm](https://user-images.githubusercontent.com/23367174/31995820-5239f758-b986-11e7-99b5-00816b2bebe8.png)

**Comment by MinaAshena** [comment]
I have the same problem.
