### ISSUE TITLE
Flickering location annonation node image while There are many location nearby

### ISSUE THREAD

**Issue by iOSMahesh** [ProjectDent/ARKit-CoreLocation#64]
![img_1631](https://user-images.githubusercontent.com/29897742/32145775-b978f138-bcf3-11e7-92c2-53d6ccb826b9.JPG)
Pls, check snap So you get an idea.

**Comment by NiteshGarg2107** [comment]
I have the same issue of flickering when nodes lie on each other.

**Comment by katunch** [comment]
Same issue here... But i haven't investigated yet

**Comment by MaticConradi** [comment]
Same here. Interestingly, the first gif on the readme page doesn't seem to have this problem. I've tried moving nodes like these just a little bit apart but that didn't help.

**Comment by JacoGasp** [comment]
Hello people,
yes we all have the same problem because all the annotations are placed at the same level in the scene. 
I recommend to have a look on this cool library https://github.com/DanijelHuis/HDAugmentedReality that is specifically designed to stack a big number of notations to avoid the overlap, even though it doesn't user ARKit.

I quickly tried to use the same algorithm used in that library and works perfectly for far annotations (above 1 km) because they are all re-placed within a circle of a fixed radius with the user in center.
Unfortunately this doesn't work for annotation closer than 1km, because is not possible to "move up" one annotation about a fixed amount of space in the vertical direction. Some trigonometric formula is needed and I'm working on it

Here what I achieved so far
https://streamable.com/ksqlv

**Comment by MaticConradi** [comment]
To be clear, the flickering happens to all nodes or only those that are more then 100m away from (0, 0, 0)?

**Comment by JacoGasp** [comment]
@MaticConradi I didn't pay attention to nodes closer than 100m, in my case is not relevant.
My biggest question is how the nodes move with the headings of the phone.

Assuming that two nodes have the same vertical position in respect of (0,0,0) and calling node1 the closest one to the user and node2 is behind node1, it happens that changing the heading of the phone node2 moves in front of node1, causing the flickering (visible on the video above). Even thought they are spaced of hundreds of meters (even km) in the real world.

I think the repositioning all the nodes in vertical direction is the solution, but I haven't fully understood yet how the nodes are positioned on the (x,z) plane and at which distance in respect of (0,0,0).

**Comment by kirti301290** [comment]
any one have solved this issue ?

**Comment by huntdo** [comment]
This is common issue referred to as "Z-Fighting". I have same issue.
https://en.wikipedia.org/wiki/Z-fighting

**Comment by huntdo** [comment]
Hi @JacoGasp Could you share code that has stack annotations for me? Thank you so much

**Comment by ashishbitcot** [comment]
I have this problem too, seems like Z-fighting is what we want to solve. Any lead please

**Comment by ProjectDent** [comment]
A solution there is either:
- solving the issue of further away nodes not being cut off, so they don’t stack
- perhaps to have their distance be relative, so it is scaled up, but things past 100m aren’t all held at 100m

**Comment by ArbabR** [comment]
@JacoGasp Can you please share how you have used ARAnnotationView in ARCL?
Thanks

**Comment by JacoGasp** [comment]
Hey @ArbabR, 
I posted some incomplete code on the slack discussion. Unfortunately, it's since a while that I cannot find time to fix/improve it. Moreover, now I would like to solve the problem setting the altitude of the POIs instead that moving the scenekit objects.
I hope to find some time in the next weeks.

**Comment by ArbabR** [comment]
Thanks for getting back @JacoGasp. I have tried that solution and the logic from HDAugmentedReality library but it didn't work in my case.

> now I would like to solve the problem setting the altitude of the POIs instead that moving the scenekit objects

That's what I thought. Best of luck with that and please do share with us your solution if you have any success.

**Comment by sungjin0213** [comment]
@ProjectDent Even with relative scale and cutting off further away ones, I'm seeing flickering issue when the nodes in same line of point of view. Is there way we can just say, "always show closer ones to the front"?

**Comment by ArbabR** [comment]
@aaronbrethorst any plans for this?

**Comment by jwilson85** [comment]
Do we have any timeline on when this issue would be fixed?

**Comment by jwilson85** [comment]
How would I go about doing a cluster icon if they start z-fighting?

**Comment by ArbabR** [comment]
@aaronbrethorst @ProjectDent is there any work around of this please?

**Comment by jwilson85** [comment]
@ArbabR So my workaround I don't know if this will work for you. But I made it so that objects that are more than 20m away scale by distance. Once again depending on your current needs, this may not be a solution for you.

**Comment by jwilson85** [comment]
@JacoGasp I looked through the HUD thing you posted could you post some sample code? I wasn't able to find what got you there.

**Comment by jwilson85** [comment]
@ArbabR  prob a dumb question but whats the channel?

**Comment by ArbabR** [comment]
@jwilson85 Please check at the bottom of repo description with **Going Forward** heading.

**Comment by sugeetgoyal** [comment]
Hi All, I am a beginner in ARKit. Using this library. I'm getting flickering issue when I add many locations. I'm using custom view as an annotation to display. Can anyone suggest me something. 
Thanks so much in advance.

**Comment by jwilson85** [comment]
@sugeetgoyal We have a few solutions in this post. I ended up doing the stacking one.

**Comment by sungjin0213** [comment]
@sugeeygoyal try to continue to search for ways to do z-fighting or z-ordering in ARKit. It should lead you to answer.

**Comment by Sephaq** [comment]
[This](https://stackoverflow.com/questions/53040089/arkit-how-to-stop-flickering-or-how-to-position-node-towards-camera?rq=1) one is a good solution.
It disables the renderingDepthBuffer from the SCNPlane, so the SCNNode RenderingOrder takes priority.
