### ISSUE TITLE
How to handle objects which are behind another object

### ISSUE THREAD

**Issue by katunch** [ProjectDent/ARKit-CoreLocation#65]
Hi 
I'm implementing a kind of POI view with ARKit-CoreLocation. In general it works great. Thanks guys. But now I came across a challenging Issue. If i have several POIs "behind" (when the user points to one direction and there are several pois). So how do I manage that i can ensure to see every POI? They should not "touch" eachother. They should stack. 

Any Ideas?

**Comment by slartibartfast101** [comment]
Hi
I gave the POI's according to their distance to the device another altitude. This is not very elegant but works in most cases.

**Comment by jagsrajput21** [comment]
@slartibartfast101 Hi. Can you tell me that how to change the altitude of POI's. I am having the same problem.

**Comment by slartibartfast101** [comment]
@jagsrajput21 Ok so with that i can help you but i have to admit that it doesn't work flawlessly.
The API i used to get the POI's gives me also the distance to the object back. Maybe in your case you need to first calculate the distance between your position and the POI. This may help:
[](https://stackoverflow.com/questions/33304340/how-to-find-out-distance-between-coordinates)

I store that information in the form of a dictionary(here distanceDict). You could also store that in a array or whatever suits you best.


```
let adjustedHight = 0.0

if distanceDict[key]! > 100 {
                
                adjustedHight += 10

            } else if distanceDict[key]! >= 200 {

adjustedHight +=20
}

let pinCoordinate = CLLocationCoordinate2D(latitude: 51.504607, longitude: -0.019592)
        let pinLocation = CLLocation(coordinate: pinCoordinate, altitude: 236 + adjustedHight)
        let pinImage = UIImage(named: "pin")!
        let pinLocationNode = LocationAnnotationNode(location: pinLocation, image: pinImage)
        sceneLocationView.addLocationNodeWithConfirmedLocation(locationNode: pinLocationNode)
        
        view.addSubview(sceneLocationView)
```

This works well for nearer distances but doesn't solve your problem if two nodes have the same coordinates. If you are also a member in the arcl slack-community i would recommend to search for "bad stacking". There are better ways than my solution.

**Comment by huntdo** [comment]
same issue, anyone help me?
