### ISSUE TITLE
Possibility to use third-party location provider ?

### ISSUE THREAD

**Issue by ddcrobert** [ProjectDent/ARKit-CoreLocation#66]
This project depends on geolocalisation's accuracy / quality.
Location Manager is fine for most outdoor usages, but it quickly becomes out of usage in dense city areas (multipaths) or indoor.
In theses situations, buildings / areas are getting equipped with third-party geolocation systems, often relying on BLE.
In order to use ARKit-CoreLocation indoor, it would be interesting to be able to input location / orientation.
The idea would be if delegate is specified, use it, otherwise use location manager.

**Comment by hallmont** [comment]
This app is meant for outdoor use anyway, but even for outdoor, accuracy is still a big issue.

**Comment by matti777** [comment]
I second this; my use case would be indoor positioning with some billboards / objects displayed on POIs in the AR view. The indoor positioning library (https://steerpath.com/) is providing the location as CLLocation objects. 

Therefore, I would see it beneficial to make the LocationManager a protocol or something to allow for the location to be provided by another kinds of implementations beyond the device GPS.

**Comment by ProjectDent** [comment]
CoreLocation supports the use of beacons natively, so they're included in the location updates from CLLocationManager.
