### ISSUE TITLE
Support for Carthage

### ISSUE THREAD

**Issue by radiodario** [ProjectDent/ARKit-CoreLocation#68]
This project is awesome. My team are trying to integrate it in a currently existing project that manages all its dependencies using Carthage. Is this something you would be interested in? we would be happy to collaborate to add support for Carthage if that's something you are happy with.

Thanks!

**Comment by radiodario** [comment]
Actually i can see there's a couple of open PR: #59 #60 so that's amazing! 👍

**Comment by TofPlay** [comment]
This is not mentioned in the README. Carthage is supported?

If it helps here are some links:
- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/DsFf6x)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Swift Cross Platform Framework](https://goo.gl/XxaJGo) 👍

May by add  add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top of the README and add section for the installation will be a great idea
