### ISSUE TITLE
Customize subview on Arkit

### ISSUE THREAD

**Issue by ddbien** [ProjectDent/ARKit-CoreLocation#71]
Hi All,
I want to add subview on Arkit as attachment image, Will I add subview to SCNNode or another way?
<img width="219" alt="screen shot 2017-12-08 at 09 56 41" src="https://user-images.githubusercontent.com/4480119/33749710-d85aa696-dc01-11e7-9710-93c1d6d2eb73.png">

Thanks All.

**Comment by ddbien** [comment]
Hi all,
Can you help me? You can give me some advice. Thanks All

**Comment by thanhnt255** [comment]
me too 👍

**Comment by adougies** [comment]
I convert my UIView to an UIImage before passing into the master branch

`func imageWithView(inView: UIView) -> UIImage? {
    UIGraphicsBeginImageContextWithOptions(inView.bounds.size, false, 0.0)
    defer { UIGraphicsEndImageContext() }
    if let context = UIGraphicsGetCurrentContext() {
      inView.layer.render(in: context)
      let image = UIGraphicsGetImageFromCurrentImageContext()
      return image
    }
    return nil
  }`

`if let viewToImage = imageWithView(inView: pinView) {
          let annotationNode = LocationAnnotationNode(location: location, image: viewToImage)
         
          sceneLocationView.addLocationNodeWithConfirmedLocation(locationNode: annotationNode)
}`
