### ISSUE TITLE
Solution for flikering nodes while overlapping each other

### ISSUE THREAD

**Issue by pareekkhushboo77** [ProjectDent/ARKit-CoreLocation#73]
what can be a good solution to solve flikering the views, can we implement clustering in that case.?

**Comment by ddbien** [comment]
I have same issue, can you help me ?

**Comment by wayn** [comment]
Same issue, anyone resolved?

**Comment by Higgins2718** [comment]
I have this problem as well

**Comment by huntdo** [comment]
This is commonly referred to as "Z-fighting" in 3D rendering, i have the same issue

**Comment by Dzionis** [comment]
@ddbien Could you share code with popup above the node?

**Comment by ashishbitcot** [comment]
I have this problem too, seems like Z-fighting is what we want to solve. Any lead please

**Comment by ProjectDent** [comment]
Duplicate of #64
