### ISSUE TITLE
Demo on iPhone X

### ISSUE THREAD

**Issue by nbawe** [ProjectDent/ARKit-CoreLocation#74]
When I ran demo on iPhone X it starts and asks permissions then briefly shows camera view and then it hangs - anybody has same problem?

**Comment by mgnt** [comment]
While I'm not using this project specifically, I am having the same problem on my own project. 

I'm at a loss as to what to do to work around it without degrading the experience, but if you don't _need_ six-degree tracking, you could change the `configuration.worldAlignment` from `.gravityAndHeading` to just `.gravity`. In this project it looks like you can try changing `orientToTrueNorth` to false (see: https://github.com/ProjectDent/ARKit-CoreLocation/blob/8f73aeaebe2cc8ab489c0a2d1a77e6a67665438c/ARKit%2BCoreLocation/Source/SceneLocationView.swift#L88 )

Hope that helps!

**Comment by nbawe** [comment]
@mgnt thanks for the answer. In my case the problem was with Compass Calibration (Settings>Privacy>Location Services>System Services)  which was somehow disabled. After enabling it every thing works as it should.

**Comment by futuretap** [comment]
Hm, I also noticed that problem even though my Compass Calibration privacy settings were OK. After a few relaunches of the app is suddenly worked. Weird.
