### ISSUE TITLE
How do I get the tapped node details?

### ISSUE THREAD

**Issue by elmz87** [ProjectDent/ARKit-CoreLocation#75]
I am trying to load a view upon tapping the node on the AR view.
Anybody have tried to do it?

**Comment by Dzionis** [comment]
@elmz87 i'm trying to implement this feature. Now i can recognize tap on the node and show node information(place name, distance) in label.

**Comment by Daltron** [comment]
@Dzionis Me and I'm sure many others would appreciate if you would show how you did this. 👍

**Comment by Dzionis** [comment]
@Daltron you can see it in my fork of this [https://github.com/Dzionis/ARKit-CoreLocation](repository). Actual version in master branch. Also, I'm trying to implement popup above the node.

**Comment by Daltron** [comment]
@Dzionis I'm getting a 404 when accessing that repo. Is it by chance private?

**Comment by Dzionis** [comment]
@Daltron Just wrong url, try now.

**Comment by Daltron** [comment]
@Dzionis great! Thank you for posting that! 👍

**Comment by emadhejazian** [comment]
//MARK: TOUCH ON NODES ACTIONS HANDLER
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        super.touchesBegan(touches, with: event)
        
        guard let touch = touches.first
            else { return }

        guard let result = sceneLocationView.hitTest(touch.location(in: sceneLocationView), options: nil).first
            else {return}
        
        if segmentAnnotationType.selectedSegmentIndex == 0 //ads
        {
            for ad in ads
            {
                if (ad.arkitNode?.contains(result.node))!
                {
                    print("This is a match")
                    let vc:PropertyProfileTableViewController =
                        UIUtils().createVC(storyBoard: "PropertyProfile",
                                           viewControllerID: "PropertProfileID") as! PropertyProfileTableViewController
                    vc.referalAdId = ad.id
                    //sceneLocationView.pause()
                    self.present(vc, animated: true, completion: {self.oritation()})
                }
            }
        }
        else if segmentAnnotationType.selectedSegmentIndex == 1 //agencies
        {
            //
        }
    }

**Comment by emadhejazian** [comment]
//MARK: TOUCH ON NODES ACTIONS HANDLER
 //add var arkitNode:SCNNode? to your object
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        super.touchesBegan(touches, with: event)
        
        guard let touch = touches.first
            else { return }

        guard let result = sceneLocationView.hitTest(touch.location(in: sceneLocationView), options: nil).first
            else {return}
        
        for ad in ads
        {
            if (ad.arkitNode?.contains(result.node))!
            {
                self.present(vc, animated: true, completion: {self.oritation()})
            }
        }
    }

**Comment by campeezjesse** [comment]
@Dzionis Thank you! I have been playing with this and still having trouble with the displaying the info. I am a complete beginner, so I am sure it is my error.  I have downloaded your workspace and added  my own coordinates to the file. 
 The location Name is displayed in the node but nothing happens on touch. Also the distance is not working but I think that is due to my map possibly.
 Thank you for your time!

**Comment by campeezjesse** [comment]
Has anyone found a way to display the annotation on the map view at the bottom of the screen as well as in the ARView?
 Sorry for all of the questions, I am learning and having a lot of fun with this demo

**Comment by ProjectDent** [comment]
@campeezjesse you can add annotations to map using standard MapKit APIs - `addAnnotation`.

https://developer.apple.com/documentation/mapkit/mkmapview/1452069-addannotation
