### ISSUE TITLE
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'

### ISSUE THREAD

**Issue by elmz87** [ProjectDent/ARKit-CoreLocation#76]
i have been trying to do a UITapGesture for the node on the SceneLocationView.
However, it returns me with the error above.

` @objc func didTapped(_ recognizer: UITapGestureRecognizer) {

        let sceneView = recognizer.view as! ARSCNView
        let touchLocation = recognizer.location(in: sceneView)
        let hitResults = sceneView.hitTest(touchLocation, options: [:])
        guard let hitResult = hitResults.first  else {
            return
        }
        let node = hitResult.node
        if let name = node.childNodes[0].name {
            print(name)
            self.selectedTeam = name
        }
        performSegue(withIdentifier: "locationDetails", sender: self)
    }`

**Comment by Dzionis** [comment]
```swift
let sceneView = self.sceneLocationView
                    let location = touch.location(in: sceneView)
                    let hitTest = sceneView.hitTest(location)
                    
                    if (!hitTest.isEmpty) {
                        let results = hitTest.first!
                        let currentNode = results.node
                        if let locationNode = getLocationNode(node: currentNode) {
                            currentLocationAnnotationNode = locationNode
                            DDLogDebug("")
                            DDLogDebug("title: \(locationNode.titlePlace!)")
                            let distance = locationNode.location.distance(from: sceneView.currentLocation()!)
                            DDLogDebug("distance: \(distance)")
                        }
                    }
                ```
