### ISSUE TITLE
Missing Map

### ISSUE THREAD

**Issue by WillRRRR** [ProjectDent/ARKit-CoreLocation#8]
Some features are missing.

![img_1219](https://user-images.githubusercontent.com/30376565/28757648-06d5c940-754d-11e7-8af4-5b1b840d38fc.PNG)

**Comment by nighthawk** [comment]
The map is only visible in the demo project if you manually set `ViewController.showMapView` to `true`.

**Comment by ProjectDent** [comment]
Duplicate of #9
