### ISSUE TITLE
Ambiguous use of 'translation(toLocation)'

### ISSUE THREAD

**Issue by paperoga** [ProjectDent/ARKit-CoreLocation#84]
I got this error in SceneLocationView at line 366.

**Comment by ProjectDent** [comment]
Which version of Xcode are you using?

**Comment by douglaswsilva** [comment]
How did you solve it?

**Comment by paperoga** [comment]
I solved simply inserting a blanc line after the statement.

**Comment by vivekshah-zymr** [comment]
Getting same error, XCode Version 9.2, and adding blank line doesn't help. Is there any other solution?

**Comment by paperoga** [comment]
Clean and rebuild.

**Comment by vivekshah-zymr** [comment]
Already did multiple times but doesn't help.

**Comment by paperoga** [comment]
Wait. I'll reopen the project soon.

**Comment by vivekshah-zymr** [comment]
Actually working fine in the downloaded demo, but gives error while integrating into my created project.

**Comment by paperoga** [comment]
Yes I know. It's normal.

**Comment by vivekshah-zymr** [comment]
So, how can I integrate this thing into my project?

**Comment by paperoga** [comment]
A suggestion it's the reverse process. Integrate your project, little segment of code, in this project.

**Comment by paperoga** [comment]
Good.
