### ISSUE TITLE
scaleRelativeToDistance = true hides the LocationAnnotationNode

### ISSUE THREAD

**Issue by SebastianKumor** [ProjectDent/ARKit-CoreLocation#86]
Hey guys, when I set the `LocationAnnotationNode`s property `scaleRelativeToDistance ` to `true` no node is displayed. When the property is set to `false` ordinary node with size 100x100 is displayed. 

When I checked in `sceneLocationViewDidUpdateLocationAndScaleOfLocationNode` delegate method the frame was 0.0 with scale 1.0.

 Any idea why is that ?

**Comment by Ksen17** [comment]
I have exactly the same problem

**Comment by ProjectDent** [comment]
@SebastianKumor @Ksen17 how far away are you placing these nodes? With `scaleRelativeToDistance` set to false, the object may be too small and too far away to see.

**Comment by SebastianKumor** [comment]
@ProjectDent  @Ksen17 My issue was that the node had the default altitude and it was just above me, therefore I have not seen it (*lol stupid me*). Also the distance and scale could be an issue if its too far. So I managed to solve it after setting this things to proper values.

**Comment by netsmith** [comment]
@SebastianKumor could you give a few more details please? Think I have a similar problem. Was you problem that the point you are looking for was directly above where you were standing or were you talking about a POI in the distance somewhere?

**Comment by fbartolom** [comment]
I have basically the same problem with a twist. I have two locationsNodes inheriting from the same superclass, one of which is regularly show and the other not. The main problem is that, apart from looking a t the sky to see if it appears, I have no other way to check what happens.
