### ISSUE TITLE
Animating nodes

### ISSUE THREAD

**Issue by eamonwhiter73** [ProjectDent/ARKit-CoreLocation#88]
I am trying to animate the nodes in my `sceneNode` and I can't get it to work, I am trying like this:

```
func sceneLocationViewDidSetupSceneNode(sceneLocationView: SceneLocationView, sceneNode: SCNNode) {
        let animation = CABasicAnimation(keyPath: "opacity")
        animation.fromValue = 100.0
        animation.toValue = 0.0
        animation.duration = 2.0
        animation.autoreverses = true
        animation.repeatCount = .infinity
        
        print("\(sceneNode) name name name name name" )
        for node in sceneNode.childNodes {
            for nodeInner in node.childNodes {
                for nodeInnermost in nodeInner.childNodes {
                    if (nodeInnermost.name?.localizedStandardContains("ship"))! {
                        print(nodeInnermost.childNodes.first ?? "FIRST DOESNT EXIST")
                        nodeInnermost.childNodes.first?.addAnimation(animation, forKey: "opac")
                    }
                }
            }
        }
    }
```

As you can see I am using the delegate method to wait until the scene is rendered and then I try to add the animations. I have also tried adding the animation to the node of the scene when it is created and added with no luck. Has anyone successfully animated a node?

**Comment by rom4in** [comment]
Yes, you need to use scnaction.

Romain

**Comment by eamonwhiter73** [comment]
can i animate opacity with scnaction?

**Comment by ProjectDent** [comment]
SCNAction is quite simple - you do something like:

let action = SCNAction.rotateby(...)
node.run(action)

There's a lot of documentation available on line for it.

**Comment by nasmuris** [comment]
I'd like to run action that moves location node by X metres, while I'm using move(to:) action, the node location is not updating within the scene as are the static nodes, is there any way how to do this?
For now, I'm setting the new location in SCNAction completition handler and moving the node to position calculated from current and future location, so the node position gets updated when the action finishes. My idea is to update the node's location simultaneously with the position as the move(to:) action does, somebody managed to solve this?
