### ISSUE TITLE
Camera is not working.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [ProjectDent/ARKit-CoreLocation#89]
Thanks for this wonderful library.

I have an issue. Camera screen is not working. 
Although, I have download demo repository and running the same.

Here is a screenshot.

![ss](https://user-images.githubusercontent.com/19154948/36474288-1587a59a-171d-11e8-846d-8fbc892db369.png)

**Comment by alexandremorgado** [comment]
@Rashesh-Bosamiya check if your compass calibration is enabled, on Settings->Privacy->Location Services->System Services->Compass Calibration

**Comment by ProjectDent** [comment]
Try deleting the app and re-installing, ensuring you accept camera permissions. Also - this won't work in simulator.

**Comment by Rashesh-Bosamiya** [comment]
It is not asking for camera permission.

**Comment by Rashesh-Bosamiya** [comment]
working fine now.

iPhone 6 Doesn't support AR based Apps.

Thanks.
