### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by WillRRRR** [ProjectDent/ARKit-CoreLocation#9]
Failed:
![img_1220](https://user-images.githubusercontent.com/30376565/28786410-c3c97bf0-75de-11e7-9352-05740bd3e684.PNG)

originally:
<img width="291" alt="screen shot 2017-07-31 at 10 54 52 am" src="https://user-images.githubusercontent.com/30376565/28786421-c92e7ece-75de-11e7-86fa-2aedef5a0cc0.png">

**Comment by ProjectDent** [comment]
It states in the readme that this library, and especially the sample project, is not the navigation demo, but it's the code that the navigation demo is built on. Navigation demo does have some maps and navigation-related features, which we're currently adding to the library.
