### ISSUE TITLE
Nodes dissapear after sceneView.session.setWorldOrigin transformation

### ISSUE THREAD

**Issue by eamonwhiter73** [ProjectDent/ARKit-CoreLocation#90]
See my question on stackoverflow (I put a bounty on it FYI): https://stackoverflow.com/questions/48919069/arkit-nodes-dissapear-after-sceneview-session-setworldorigin-transformation

I am wondering if anyone can answer that question?

**Comment by rom4in** [comment]
How do you know the nodes are “removed”?

Transforms change the position, rotation and SCALE…could you have scaled your scene’s root node to 0 by any chance?..
Once way to know for sure would be to call scene.scale = SCNVector3Make(1,1,1) after you set the world origin maybe.

**Comment by eamonwhiter73** [comment]
Thanks for the response, the thing with scale is, with what I am testing, I am not translating the position very far...so it shouldn't go out of view like that because of scale but I'll check anyway

**Comment by eamonwhiter73** [comment]
I dont think there is a `scene.scale`...is `sceneView.contentScaleFactor` what you are talking about? I tried it set at 1.0 and no luck...also my AR objects freeze (the screen freezes) once the transform is made...this is also happening for `sceneView.scene.rootNode.transform` (tryin to transform the objects position instead of the world origin...also...I should mention I am using iBeacons for location detection. I only have 2 right now so I am simulating the 3rd, with a made up point and distance that makes sense, to test trilateration (using the points of the beacon and the estimated distances from the beacons)....this is the code I have now:

```
func locationManagerDidRangeBeacons(_ locationManager: CLLocationManager, beacons: [CLBeacon], region: CLBeaconRegion) {
        print("\(beacons) + beacons for ranging")
        if beacons.count > 0 {
            let nearestBeacon = beacons.first!
            let major = CLBeaconMajorValue(truncating: nearestBeacon.major)
            let minor = CLBeaconMinorValue(truncating: nearestBeacon.minor)
            
            print("major: \(major)")
            print("minor: \(minor)")
            print("accuracy: \(nearestBeacon.accuracy)")
            
            switch nearestBeacon.proximity {
            case .immediate:
                print("--- immediate ---")
            case .near:
                print("--- near ---")
            case .far:
                print("--- far ---")
            case .unknown:
                print("--- proximity unknown ---")
            }
            
            for beacon in beacons {
                guard beacon.accuracy != -1.0 else {
                    return
                }
            }
            
            if (nearestBeacon.proximityUUID.uuidString == "12345678-B644-4520-8F0C-720EAF059935") {
                self.latestAccuracyA = nearestBeacon.accuracy
            }
            else {
                self.latestAccuracyB = nearestBeacon.accuracy
            }
            
            if self.latestAccuracyA != nil && self.latestAccuracyB != nil {
                
                let myPosition: Point = Utilities.trilateration(point1: Point(xx: -2.5, yy: 0.0), point2: Point(xx: 2.0, yy: 2.0), point3: Point(xx: 0.0, yy: 0.0), r1: latestAccuracyA, r2: latestAccuracyB, r3: 2.0)
                
                var m = matrix_float4x4()
                m.columns.0 = [1.0, 0.0, 0.0, 0.0]
                m.columns.1 = [0.0, 1.0, 0.0, 0.0]
                m.columns.2 = [0.0, 0.0, 1.0, 0.0]
                m.columns.3 = [Float(myPosition.x!), 0.0, Float(myPosition.y!), 1.0]
                
                print("\(myPosition.x) --- x")
                print("\(myPosition.y) --- y")
                
                sceneView.scene.rootNode.setWorldTransform(SCNMatrix4(
                    m11: 1.0, m12: 0.0, m13: 0.0, m14 :0.0,
                    m21: 0.0, m22: 1.0, m23: 0.0, m24: 0.0,
                    m31: 0.0, m32: 0.0, m33: 1.0, m34: 0.0,
                    m41: Float(myPosition.x!), m42: 0.0, m43: Float(myPosition.y!), m44: 1.0
                ))
            }
        }
    }
```

Once it ranges the beacons and satisfies the latestAccuracyA/B "no-nil" condition...the ar objects on the screen freeze...the screen behind them is black...but I can see in the console it continues to run...ranging the beacons...probably causing this problem in a perpetual way.

**Comment by eamonwhiter73** [comment]
i just realized this topic is slightly irrelevant to the core location project because i am using ibeacons...i guess I am wondering if anyone knows how to continuously transform either the world or the objects.
