### ISSUE TITLE
Subclassing to access ARSCNView delegate functions

### ISSUE THREAD

**Issue by BildPeter** [ProjectDent/ARKit-CoreLocation#91]
If I want to access the renderer() functions of ARSCNView, I can either just 'hack' directly into the SceneLocationView.swift (works), or it is suggested to subclass. But this is not possible in the current implementation. With the error:
`Cannot inherit from non-open class 'SceneLocationView' outside of its defining module`
`Cannot override SceneLocationView: It is public in ARCL`

Does the structure of SceneLocationView has to be changed, or is there another way access 
`func renderer( _ renderer : SCNSceneRenderer, didAdd node : SCNNode, for anchor : ARAnchor )`
`func renderer( _ renderer : SCNSceneRenderer, updateAtTime time : TimeInterval )`

**Comment by michael-martinez** [comment]
I am having exactly the same problem, we should be able to write custom messages to user if session fails or whatever, I am currently forwarding all the events through an ARSCNViewDelegate created in SceneLocationView.

**Comment by AakashSareen** [comment]
well, if the intention was that people should subclass SceneLocationView it needs to be declared as open. 
I had the same issue, ended up importing code manually and making changes directly :/

**Comment by intere** [comment]
feel free to submit a PR to address this.  It would be very helpful, the authors don't always anticipate all use cases.

**Comment by intere** [comment]
addressed in https://github.com/ProjectDent/ARKit-CoreLocation/pull/206
