### ISSUE TITLE
Question on - Fixing Heading with Recent Location Data

### ISSUE THREAD

**Issue by hazzaldo** [ProjectDent/ARKit-CoreLocation#92]
Sorry I just wanted to clarify the explanation in "Fixing Heading with Recent Location Data" in the wiki page: 

Question 1, quoting from the section:
```
"We have our determined location using GPS + AR, and we have this new location data point."
```
The `determined location using GPS + AR`, is this the last best location estimate retrieved of the user's location?

`and we have this new location data point`, is this the new location value given by Core Location (CLLocationManager)?

Question 2:

```
The problem is we're now outside of the new location data point's range`
```
I'm confused. How did we suddenly became outside of the new location data point range? On what basis?

Question 3:
```
So we have 2 lines of travel:

between the 2 data points
between the first data point and our determined location.
```
A- What are these `2 data points`? Could you elaborate please?
B- `between the first data point and our determined location.` . The `first data point` being previous fetched best estimate user locations. And `our determined location` is our last best estimate user location? 
Otherwise please explains what this means? 

Many thanks in advance.

**Comment by intere** [comment]
## Question 1
> Yes

## Question 2
> I believe it's due to movement - and this is a hypothetical assumption that we've moved beyond the location data point's range, but I'm not certain.

## Question 3A
> First data point: We receive a location data point.
> Second data point: We move north by 10m through the scene. We receive another location data point.

## Question 3B
> This is to highlight that ARKit determines your approximate location using CoreMotion, but moving 10 meters introduces a margin of error.  CoreLocation also determines your location (via the GPS).  There will be a margin of error between what CoreLocation and ARKit believe your location is and therefore the mismatch needs to be addressed.
