### ISSUE TITLE
Question on True North manual overriding functions

### ISSUE THREAD

**Issue by hazzaldo** [ProjectDent/ARKit-CoreLocation#93]
Sorry maybe I'm missing something here, but I couldn't help notice regarding the functions below, shouldn't this be the other way around i.e. clockwise is where you `add` degrees and `anti-clockwise` is where you subtract degrees. If your initial heading is north heading i.e. 0 degree (or 360), if you change your heading by further 5 degrees clockwise, that will be 5 degrees, that's adding 5 to 0. If you continue changing clockwise you continue adding degrees. But if you change your heading by 5 degree anti-clockwise, you deduct 5 from 360, to get 355 degrees. And if you keep changing degrees anti-clockwise, you have to keep deducting. Or am I missing something?!!

```
///Moves the scene heading clockwise by 1 degree
    ///Intended for correctional purposes
    func moveSceneHeadingClockwise() {
        sceneNode?.eulerAngles.y -= Float(1).degreesToRadians
    }
    
    ///Moves the scene heading anti-clockwise by 1 degree
    ///Intended for correctional purposes
    func moveSceneHeadingAntiClockwise() {
        sceneNode?.eulerAngles.y += Float(1).degreesToRadians
    }
```

**Comment by intere** [comment]
@hazzaldo - it's likely that for the y-axis, it's the opposite.  Remember that clockwise and counter clockwise are relative to the way you're facing.  Look at a clock the way it's intended, and the hands move "clockwise".  Look at it from behind (think of a transparent clock) and the hands move counter-clockwise (from your perspective).
