### ISSUE TITLE
Question on addLocationNodeWithConfirmedLocation function

### ISSUE THREAD

**Issue by hazzaldo** [ProjectDent/ARKit-CoreLocation#94]
Just wondering, is there any chance or a scenario where the location of the node is confirmed but yet the location of the node is `nil`? 

```
public func addLocationNodeWithConfirmedLocation(locationNode: LocationNode) {
        if locationNode.location == nil || locationNode.locationConfirmed == false {
            return
        }
```

**Comment by intere** [comment]
I'm not sure - have you tested this to see @hazzaldo ?  FYI - I'm going to close this issue due to it's age.
