### ISSUE TITLE
LocationAnnotationNode Fixed at User's Position

### ISSUE THREAD

**Issue by azamsharp** [ProjectDent/ARKit-CoreLocation#96]
I am running the following code and no matter what I do the pin appears extremely large and it is fixed at the origin (0,0,0). Any ideas?

class ViewController: UIViewController {

    let sceneLocationView = SceneLocationView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        sceneLocationView.run()
        
        self.view.addSubview(sceneLocationView)
        addAnnotation()
    }
    
    private func addAnnotation() {
        
        let coordinate = CLLocationCoordinate2D(latitude: 29.967687, longitude: -95.502090)
        
        let location = CLLocation(latitude: coordinate.latitude, longitude: coordinate.longitude)
        
        let annotationNode = LocationAnnotationNode(location: location, image: UIImage(named :"pin")!)
        
        annotationNode.scaleRelativeToDistance = false
    
        sceneLocationView.addLocationNodeWithConfirmedLocation(locationNode: annotationNode)
    }

**Comment by yoavschwartz** [comment]
Did you find a solution? I encountered the same thing now
