### ISSUE TITLE
LocationNode is traveling with you.

### ISSUE THREAD

**Issue by ArbabR** [ProjectDent/ARKit-CoreLocation#97]
I have downloaded the project from the master branch but having the following issues

1- I have placed a node on some lat-long but as I move in any direction, nodes updates and travel with me. How to fix that node on given lat-long?

2- Default altitude value is 236 if I decrease the value to 0, 50 or 100 the node never appear on that lat-long at all.

I haven't changed anything in the code its the same which I have downloaded from the project only the Location (lat-long) is changed.

**Comment by KaiHuebner** [comment]
I had the same problem.

Forgot to set **NSLocationWhenInUseUsageDescription** in **Info.plist**

**Comment by danglq** [comment]
I met the same this problem.
Did you have any solution?

**Comment by ArbabR** [comment]
@danglq nops not yet.

**Comment by ArbabR** [comment]
Closing this. The issue was on my side.

**Comment by ianpaclawson** [comment]
@ArbabR Would you mind sharing your solution? I'm experiencing the same issue, still trying to solve it.

**Comment by ArbabR** [comment]
1- It looks like its travelling with you but it's not. If you move towards it, the node will be at the same lot-long you have placed.

2- I have checked my device altitude from the location services is 210 value so I am giving device altitude instead of a hardcoded value i.e 236. If I give a lower value than my device's altitude the node will not appear.
