### ISSUE TITLE
currentLocation() is nil 

### ISSUE THREAD

**Issue by azamsharp** [ProjectDent/ARKit-CoreLocation#98]
self.sceneLocationView.currentLocation() is nil. Anyone else facing the same issue?

**Comment by scm573** [comment]
Same. Now I'm just retrieving the current location by myself.

**Comment by HarrisonRenny** [comment]
The first current location is added when the render runs for the first time. Are you calling the function before the view appears?

**Comment by intere** [comment]
Closing due to being old and stale.
