### ISSUE TITLE
Compile error in Xcode 9.3 / Swift 4.1

### ISSUE THREAD

**Issue by scm573** [ProjectDent/ARKit-CoreLocation#99]
Must exhaust the new ARCamera.TrackingState.Reason: .limited(.relocalizing)

[https://github.com/ProjectDent/ARKit-CoreLocation/blob/master/ARKit+CoreLocation/Source/SceneLocationView.swift#L478](url)

**Comment by AntonRohr** [comment]
This is addressed and fixed in Pull Request #95

**Comment by scm573** [comment]
Yeah, thanks for the PR.
Hope it could be merged soon.

**Comment by AntonRohr** [comment]
The last commit is from December, so I doubt it.
